import {useCallback,useEffect,useLayoutEffect,useRef,useState} from 'react';
import {getMemberScopedActivityEvents,getConversationSession,memberAction,abortMember,type ConversationSessionInfo} from '../api/client';
import {formatToolArgsFull,summarizeAgentEvent,type AgentEvent} from '../components/agent-event-utils';
import {activityLabel,activityRecordKey,activityRecords,activityStatus,mergeActivityEvents} from './activity-records';
import {activityView,type ActivityView} from './pane-state';
import {Avatar,Icon,IconButton,Menu,MenuItem,Modal,copyText,errorText} from './ui';
const names={stop:'停止工作',compact:'压缩会话',restart:'重启成员',reset:'重置会话'};
function Mark({text,query}:{text:string;query:string}){const at=query?text.toLocaleLowerCase().indexOf(query.toLocaleLowerCase()):-1;return at<0?<>{text}</>:<>{text.slice(0,at)}<mark>{text.slice(at,at+query.length)}</mark>{text.slice(at+query.length)}</>;}
function fullTime(ts?:number){return ts?new Date(ts).toLocaleString('zh-CN',{hour12:false}):'时间未提供';}
export function Activity({id,scope,find,onCloseFind}:{id:string;scope:string;find:boolean;onCloseFind:()=>void}) {
 const view=useRef(activityView(id,scope)).current;
 const [session,setSession]=useState<ConversationSessionInfo|null>(null),[events,setEvents]=useState<AgentEvent[]>(view.events),[before,setBefore]=useState(view.before),[hasMore,setHasMore]=useState(view.hasMore),[query,setQuery]=useState(view.query),[open,setOpen]=useState(view.openId),[busy,setBusy]=useState(false),[loading,setLoading]=useState(!view.events.length),[olderBusy,setOlderBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[menu,setMenu]=useState<{x:number;y:number}|null>(null),[confirm,setConfirm]=useState<'reset'|'restart'|null>(null);
 const list=useRef<HTMLDivElement>(null),alive=useRef(true),epoch=useRef(0),initial=useRef(true),previousFind=useRef(find),anchor=useRef<{height:number;top:number}|null>(null);
 const load=useCallback(async()=>{const ticket=++epoch.current;try{const [s,page]=await Promise.all([getConversationSession(scope,id),getMemberScopedActivityEvents(id,scope,120)]);if(!alive.current||ticket!==epoch.current)return;setSession(s);const incoming=page.events as AgentEvent[];const old=new Set(view.events.map(e=>JSON.stringify(e)));if(!view.events.length||page.hasMore&&!incoming.some(e=>old.has(JSON.stringify(e)))){setBefore(page.nextBeforeSeq??undefined);setHasMore(page.hasMore);}setEvents(previous=>mergeActivityEvents(previous,incoming));setError('');}catch(e){if(alive.current&&ticket===epoch.current)setError(errorText(e));}finally{if(alive.current&&ticket===epoch.current)setLoading(false);}},[scope,id]);
 useEffect(()=>{alive.current=true;void load();const timer=setInterval(()=>void load(),4000);return()=>{alive.current=false;epoch.current++;clearInterval(timer);};},[load]);
 useEffect(()=>{view.events=events.slice(-1000);view.before=before;view.hasMore=hasMore;view.query=query;view.find=find;view.openId=open;},[events,before,hasMore,query,find,open]);
 useLayoutEffect(()=>{const el=list.current;if(!el)return;if(anchor.current){el.scrollTop=anchor.current.top+el.scrollHeight-anchor.current.height;anchor.current=null;}else if(initial.current&&!loading){el.scrollTop=view.scroll;initial.current=false;}},[events,loading]);
 useLayoutEffect(()=>{if(find&&!previousFind.current){view.baseScroll=list.current?.scrollTop??0;document.getElementById('gwInput')?.focus();}else if(!find&&previousFind.current){setQuery('');requestAnimationFrame(()=>{if(list.current)list.current.scrollTop=view.baseScroll;document.getElementById('gwFindControl')?.focus({preventScroll:true});});}previousFind.current=find;},[find]);
 const operate=async(kind:keyof typeof names)=>{setConfirm(null);setMenu(null);setBusy(true);setNotice('');try{const result=kind==='stop'?await abortMember(id):await memberAction(id,kind);if(!alive.current)return;setNotice((result as {message?:string}).message||`${names[kind]}请求已处理。`);await load();}catch(e){if(alive.current)setError(errorText(e));}finally{if(alive.current)setBusy(false);}};
 const term=query.trim(),records=activityRecords(events).map(record=>{const status=activityStatus(record.event,record.end),corpus=[activityLabel(record.event),status.label,formatToolArgsFull(record.event.args),formatToolArgsFull(record.end?.result??record.event.result)].join('\n');return {...record,status,corpus};}).filter(record=>!term||record.corpus.toLocaleLowerCase().includes(term.toLocaleLowerCase()));
 return <>
  <div className="gw-hero"><Avatar id={id} size={76} status={session?.status} animated/></div><section className="gw-controls" aria-label="成员操作"><div className="gw-control-row"><span className="gw-state" role="status">{session?session.busy.busy?'工作中':'待命':'正在同步状态…'}</span><button className="gr-button" disabled={busy||!session?.busy.busy} onClick={()=>void operate('stop')}><Icon name="stop"/>停止工作</button><IconButton icon="ellipsis" label="更多操作" disabled={busy||!session} onClick={e=>{const r=e.currentTarget.getBoundingClientRect();setMenu({x:r.left-180,y:r.bottom});}}/></div><p className="gw-impact">作用于该成员的所有聊天；停止、重启、重置会取消待处理工作。</p>{notice&&<p className="gw-outcome" role="status">{notice}</p>}{error&&<p className="gr-error" role="alert">{error} <button onClick={()=>void load()}>重试</button></p>}</section>
  {find&&<div className="gw-search"><Icon name="search"/><input id="gwInput" type="search" aria-label="查找本页工作记录" placeholder="查找工作记录" value={query} onChange={e=>{setQuery(e.target.value);if(list.current)list.current.scrollTop=0;}} autoFocus/><span id="gwCount" className="gw-count" role="status">{term?`${records.length} 条匹配`:''}</span><IconButton icon="close" label="关闭工作记录查找" onClick={onCloseFind}/></div>}<div className="gw-scope">成员工作记录</div>
  <div className="gw-list" ref={list} tabIndex={0} aria-label="工作记录列表" onScroll={e=>{if(!loading)view.scroll=e.currentTarget.scrollTop;}}>
   {hasMore&&<button className="gr-load-older" disabled={olderBusy} onClick={async()=>{setOlderBusy(true);try{const page=await getMemberScopedActivityEvents(id,scope,120,before);if(!alive.current)return;if(list.current)anchor.current={height:list.current.scrollHeight,top:list.current.scrollTop};setEvents(previous=>mergeActivityEvents(page.events as AgentEvent[],previous));setBefore(page.nextBeforeSeq??undefined);setHasMore(page.hasMore);}catch(e){if(alive.current)setError(errorText(e));}finally{if(alive.current)setOlderBusy(false);}}}>{olderBusy?'正在读取…':'加载更早记录'}</button>}
   {!records.length&&<p className="gw-empty">{loading?'正在读取工作记录…':term?'没有匹配记录':'暂无工作记录'}</p>}
   <div className="gw-accordion">{records.map(({event,end,status,corpus})=>{const key=activityRecordKey(event),summary=summarizeAgentEvent(end??event),at=term?corpus.toLocaleLowerCase().indexOf(term.toLocaleLowerCase()):-1,excerpt=term&&!`${activityLabel(event)} ${status.label}`.toLocaleLowerCase().includes(term.toLocaleLowerCase())?corpus.slice(Math.max(0,at-25),at+term.length+65):'';return <details className="gw-record" name={`gw-records-${id}`} key={key} data-record={key} open={open===key}><summary onClick={event=>{event.preventDefault();setOpen(previous=>{const next=previous===key?null:key;view.openId=next;return next;});}}><span className="gw-status-icon" data-status={status.kind} aria-hidden="true">{status.kind==='missing'?<span>?</span>:status.kind==='interrupted'?<span className="gw-status-dot"/>:<Icon name={status.kind==='error'?'close':'check'}/>}</span><span className="gw-action"><span className="gw-action-label" title={activityLabel(event)}><Mark text={activityLabel(event)} query={term}/></span><time title={fullTime(event.ts)}>{event.ts?new Date(event.ts).toLocaleTimeString('zh-CN',{hour12:false}):'时间未提供'}</time>{excerpt&&<small className="gw-match"><Mark text={excerpt} query={term}/></small>}</span><span className="gw-result" data-status={status.kind}><Mark text={status.label} query={term}/></span><span className="gw-chevron"><Icon name="chevron-down"/></span></summary><div className="gw-detail"><div className="gw-facts"><span>{event.toolName??event.type}</span><span>记录 {String(event.toolCallId??event.seq??'未提供')}</span><span>开始：{fullTime(event.ts)}</span>{end?.ts&&<span>结束：{fullTime(end.ts)}</span>}</div>{event.args===undefined?<p className="gw-detail-note">参数未记录</p>:<RecordBlock title="参数" text={formatToolArgsFull(event.args)} view={view} record={key} onNotice={setNotice}/>}<RecordBlock title="输出" text={formatToolArgsFull(end?.result??event.result??event.text??event.thinking??summary.detail??'未记录')} view={view} record={key} onNotice={setNotice}/>{status.kind==='missing'&&<p className="gw-detail-note">记录中没有返回结果，不能据此判断是否仍在执行。</p>}{(event.truncated===true||end?.truncated===true)&&<p className="gw-detail-note">此条记录的输出已截断，不是完整输出。</p>}</div></details>;})}</div>
  </div>
  {menu&&<Menu {...menu} onClose={()=>setMenu(null)}>{(['compact','restart','reset'] as const).map(kind=><MenuItem key={kind} onClick={()=>kind==='compact'?void operate(kind):(setMenu(null),setConfirm(kind))}>{names[kind]}</MenuItem>)}</Menu>}
  {confirm&&<Modal title={`${names[confirm]} ${session?.memberName??'成员'}？`} onClose={()=>setConfirm(null)}><p>{confirm==='reset'?'结束当前工作并重置上下文，下次从新会话开始。':'结束当前工作并重新加载成员，已有上下文保留。'}</p><p>这会影响该成员的所有聊天，并取消尚未处理的工作。历史消息和成员资料不删除；已执行的外部操作不会撤回，后台命令可能继续运行。</p><div className="gr-dialog-actions"><button className="gr-button" onClick={()=>setConfirm(null)}>取消</button><button className="gr-button gr-primary" onClick={()=>void operate(confirm)}>{names[confirm]}</button></div></Modal>}
 </>;
}
function RecordBlock({title,text,view,record,onNotice}:{title:string;text:string;view:ActivityView;record:string;onNotice:(message:string)=>void}) {
 const pre=useRef<HTMLPreElement>(null),key=`${record}:${title}`;
 useLayoutEffect(()=>{const saved=view.blocks.get(key);if(pre.current&&saved){pre.current.scrollTop=saved.top;pre.current.scrollLeft=saved.left;}},[key,text]);
 return <section className="gw-block"><header><span>{title}</span><IconButton icon="copy" label={`复制${title}`} onClick={()=>void copyText(text).then(ok=>onNotice(ok?'已复制':'未能复制，请手动复制'))}/></header><pre ref={pre} tabIndex={0} aria-label={`${title}原文`} onScroll={e=>view.blocks.set(key,{top:e.currentTarget.scrollTop,left:e.currentTarget.scrollLeft})}>{text}</pre></section>;
}
