import {useEffect,useState} from 'react';
import type {OAuthLoginJob} from '../api/client';
import {Icon,copyText} from './ui';
function safeUrl(raw?:string){try{const url=new URL(raw??'');return ['http:','https:'].includes(url.protocol)&&!url.username&&!url.password?url.href:'';}catch{return '';}}
export function AuthFields({job,name,setName,code,setCode,busy,error,onStart,onCancel,onSubmit,onRetryRead,onNotice}:{job:OAuthLoginJob|null;name:string;setName:(value:string)=>void;code:string;setCode:(value:string)=>void;busy:boolean;error:string;onStart:()=>void;onCancel:()=>void;onSubmit:(value:string)=>void;onRetryRead:()=>void;onNotice:(message:string)=>void}) {
 const [opened,setOpened]=useState(false),[manualOpen,setManualOpen]=useState(false);
 useEffect(()=>{setOpened(false);setManualOpen(false);},[job?.id]);
 const active=!!job&&!['completed','failed','cancelled'].includes(job.status),url=safeUrl(job?.deviceCode?.verificationUri??job?.authUrl),host=url?new URL(url).host:'',extra=!!job?.inputRequested&&!job.selectPrompt&&!job.authUrl&&!job.deviceCode,manual=!!job?.inputRequested&&!job.selectPrompt&&!!job.authUrl&&!job.deviceCode;
 const status=!job?busy?'正在开始授权…':'等待开始授权。':job.status==='failed'?job.error||'授权失败':job.status==='cancelled'?'授权已取消，尚未保存。':job.status==='completed'?'授权已完成，正在确认接入…':job.status==='starting'?'正在确认授权结果…':job.selectPrompt?'请选择登录方式。':extra?'请补充登录信息。':job.deviceCode?'等待设备授权':'等待浏览器授权';
 return <>
  <form id="maExtraForm" onSubmit={event=>{event.preventDefault();if(extra)onSubmit(code);}}><div className="gr-settings-card"><div className="gr-setting-row ma-entry-row"><label htmlFor="maAuthName">接入名称</label><input id="maAuthName" className="ma-control" maxLength={80} value={name} disabled={busy} onChange={event=>setName(event.target.value)}/></div>{host&&<div className="gr-setting-row ma-site-row"><span>授权网站</span><span>{host}</span></div>}{job?.deviceCode&&<div className="gr-setting-row ma-device-row"><span>设备码</span><div><code>{job.deviceCode.userCode}</code><button className="gr-button" type="button" disabled={!active||busy} onClick={()=>void copyText(job.deviceCode!.userCode).then(ok=>onNotice(ok?'已复制设备码':'未能复制，请手动复制'))}>复制</button></div></div>}{extra&&<div className="gr-setting-row ma-entry-row"><label htmlFor="maExtraInput">{job?.providerId==='github-copilot'?'企业域名':job?.prompt}</label><input id="maExtraInput" type={job?.inputSecret?'password':'text'} className="ma-control" autoComplete="off" spellCheck={false} placeholder={job?.inputPlaceholder??(job?.providerId==='github-copilot'?'留空使用 github.com':undefined)} value={code} disabled={busy} onChange={event=>setCode(event.target.value)}/></div>}</div>{extra&&<div className="ma-add-actions"><button className="gr-button gr-primary" disabled={busy||!job?.allowEmpty&&!code.trim()}>继续</button></div>}</form>
  <p className="ma-note">{job?.deviceCode?'在供应商网页输入设备码并确认授权。':'授权在供应商网页完成；不要把账户密码填入这里。'}</p>
  <p className={`ma-auth-status ${job?.status==='failed'?'ma-error':''}`} role="status">{status}</p>
  {job?.selectPrompt&&job.inputRequested&&<div className="gr-settings-card ma-list ma-auth-choices" aria-label={job.selectPrompt.message}>{job.selectPrompt.options.map(option=><button className="gr-setting-row ma-row" disabled={busy} key={option.id} onClick={()=>onSubmit(option.id)}><span>{option.label}</span><Icon name="chevron-right"/></button>)}</div>}
  <div className="ma-auth-actions">{url&&active&&<a className="gr-button gr-primary" href={url} target="_blank" rel="noopener noreferrer" onClick={()=>setOpened(true)}>{opened?'重新打开授权网页':job?.deviceCode?'前往授权':'打开授权网页'}</a>}{active&&<button type="button" className="gr-button" disabled={busy} onClick={onCancel}>取消授权</button>}{!active&&job?.status!=='completed'&&<button type="button" className="gr-button gr-primary" disabled={busy} onClick={onStart}>{job?'重新开始':'开始授权'}</button>}</div>
  {manual&&<details id="maManualDetails" className="ma-flow-details" open={manualOpen} onToggle={event=>setManualOpen(event.currentTarget.open)}><summary>无法自动返回？</summary><form id="maManualForm" onSubmit={event=>{event.preventDefault();onSubmit(code);}}><label htmlFor="maAuthInput">授权码或回跳地址</label>{job?.inputSecret?<input id="maAuthInput" type="password" className="ma-control" autoComplete="off" value={code} disabled={busy} onChange={event=>setCode(event.target.value)}/>:<textarea id="maAuthInput" className="ma-control" autoComplete="off" spellCheck={false} value={code} disabled={busy} placeholder={job?.inputPlaceholder??'粘贴供应商返回的授权码或完整回跳地址'} onChange={event=>setCode(event.target.value)}/>}<div className="ma-auth-actions"><button className="gr-button" disabled={busy||!job?.allowEmpty&&!code.trim()}>提交</button></div></form></details>}
  {error&&<p className="ma-error" role="alert">{error}{job?.status==='completed'&&<button className="gr-button" type="button" onClick={onRetryRead}>重试确认</button>}</p>}
 </>;
}
