import {useState,type CSSProperties} from 'react';
import {patchGlobalMember,type MemberDetail} from '../api/client';
import {Avatar,Modal,errorText} from './ui';
import {PERSONA_SHAPE_PATHS,resolvePersonaColor,resolvePersonaShape} from './vendor/character-study';
const colors:Record<string,string>={black:'#000000',brown:'#a27952',red:'#ff3e51',orange:'#ff781c',yellow:'#ffaf38',green:'#00c972',cyan:'#1cc3b0',blue:'#2a92fe',violet:'#a97efe',magenta:'#ff5eb1',gray:'#959595'};
const colorLabels:Record<string,string>={black:'黑色',brown:'棕色',red:'红色',orange:'橙色',yellow:'黄色',green:'绿色',cyan:'青色',blue:'蓝色',violet:'紫色',magenta:'粉色',gray:'灰色'};
const shapeLabels:Record<string,string>={blob:'圆形',pebble:'卵石',squircle:'圆方形',tablet:'胶囊',wedge:'圆角三角',hex:'六边形',cloud:'云朵',teardrop:'水滴'};
export function AvatarPicker({member,onClose,onSaved}:{member:MemberDetail;onClose:()=>void;onSaved:(member:MemberDetail)=>void}) {
  const [color,setColor]=useState(resolvePersonaColor(member.memberId,member.avatarColor)),[shape,setShape]=useState(resolvePersonaShape(member.memberId,member.avatarShape)),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const save=async(reset=false)=>{if(busy)return;setBusy(true);setError('');try{const result=await patchGlobalMember(member.memberId,{avatarShape:reset?null:shape,avatarColor:reset?null:color});onSaved(result.member);onClose();}catch(e){setError(errorText(e));}finally{setBusy(false);}};
  return <Modal title="头像" onClose={()=>{if(!busy)onClose();}}><div className="gr-avatar-preview"><Avatar id={member.memberId} size={84} color={color} shape={shape} animated/></div><div className="gr-color-grid">{Object.entries(colors).map(([id,value])=><button type="button" key={id} className="gr-color-dot" style={{'--color':value} as CSSProperties} aria-label={colorLabels[id]} aria-pressed={color===id} disabled={busy} onClick={()=>setColor(id)}/>)}</div><div className="gr-shape-grid">{Object.entries(PERSONA_SHAPE_PATHS).map(([id,path])=><button type="button" key={id} className="gr-shape-choice" aria-label={shapeLabels[id]} aria-pressed={shape===id} disabled={busy} onClick={()=>setShape(id)}><svg viewBox="-15 -15 259 259" aria-hidden="true"><path d={path}/></svg></button>)}</div>{error&&<p className="gr-error" role="alert">{error}</p>}<div className="gr-dialog-actions"><button className="gr-button" disabled={busy} onClick={()=>void save(true)}>恢复默认</button><button className="gr-button" disabled={busy} onClick={onClose}>取消</button><button className="gr-button gr-primary" disabled={busy} onClick={()=>void save()}>{busy?'正在保存…':'保存'}</button></div></Modal>;
}
