import { Fragment, useCallback, useEffect, useLayoutEffect, useRef, useState } from 'react';
import { getArtifactRawBlob, postConversationRead, type ChatEntry, type RoomContact, type RoomMessage } from '../api/client';
import { messages as loadMessages } from './api';
import { Avatar, GroupAvatar, Icon, IconButton, Markdown, copyText, errorText } from './ui';
import { attachmentFile, FileCards, type ViewFile } from './Files';
import { Composer } from './Composer';
import { Search } from './Search';
import { updateDraft, getDraft } from './drafts';
import {quoteMention,withQuoteMention} from './mention-draft';
const views=new Map<string,{anchor?:string;offset:number;atBottom:boolean}>();
export function clearChatViews(){views.clear();}
function rememberPosition(el:HTMLDivElement|null,key:string,atBottom:boolean){if(!el?.getClientRects().length||!el.clientHeight)return;const bounds=el.getBoundingClientRect(),anchor=[...el.querySelectorAll<HTMLElement>('[data-message-id]')].find(row=>row.getBoundingClientRect().bottom>bounds.top);views.set(key,{anchor:anchor?.dataset.messageId,offset:anchor?anchor.getBoundingClientRect().top-bounds.top:0,atBottom});}
export type Incoming = {scope:string;message:RoomMessage;version:number};
export function Chat({chat,contacts,memberIds,username,connected,incoming,onSent,onPane,onFile,onNav,onToast,onChanged}:{chat:ChatEntry;contacts:RoomContact[];memberIds:string[];username:string;connected:boolean;incoming:Incoming|null;onSent:(scope:string,msg:RoomMessage)=>void;onPane:(kind:'profile'|'activity'|'assets')=>void;onFile:(files:ViewFile[],index:number)=>void;onNav:()=>void;onToast:(s:string)=>void;onChanged:()=>void}) {
  const scope=chat.scopeId,[rows,setRows]=useState<RoomMessage[]>([]),[loading,setLoading]=useState(true),[more,setMore]=useState(false),[error,setError]=useState(''),[search,setSearch]=useState(false),[history,setHistory]=useState(false),[unseen,setUnseen]=useState(false),[scrolled,setScrolled]=useState(false),[drag,setDrag]=useState(false);
  const transcript=useRef<HTMLDivElement>(null),nearBottom=useRef(true),epoch=useRef(0),dragDepth=useRef(0),busyOlder=useRef(false),follow=useRef(true),pendingJump=useRef(''),restoreOffset=useRef<number|null>(null),wasConnected=useRef(connected);
  const viewKey=username+'|'+scope,lastRead=useRef(''),readNow=useRef(()=>{});
  const visible=()=>{const el=transcript.current,app=el?.closest('.gr-app') as HTMLElement|null;return !!el?.getClientRects().length&&el.clientHeight>0&&document.visibilityState==='visible'&&!document.querySelector('dialog[open]')&&!app?.hasAttribute('data-nav')&&!(app?.dataset.pane&&innerWidth<=820);};
  const markRead=()=>{const last=rows.at(-1),el=transcript.current;if(!loading&&last)rememberPosition(el,viewKey,nearBottom.current);if(!last||!el||!connected||loading||history||!visible()||el.scrollHeight-el.scrollTop-el.clientHeight>4)return;const key=scope+'|'+last.id;if(lastRead.current===key)return;lastRead.current=key;void postConversationRead(scope,{messageId:last.id,seq:last.seq}).then(onChanged).catch(()=>{if(lastRead.current===key)lastRead.current='';});};
  readNow.current=markRead;
  useEffect(()=>{const update=()=>readNow.current();document.addEventListener('visibilitychange',update);window.addEventListener('focus',update);return()=>{document.removeEventListener('visibilitychange',update);window.removeEventListener('focus',update);};},[]);
  const latest=useCallback(async(restore=false)=>{const ticket=++epoch.current;setLoading(true);setError('');try{const saved=restore?views.get(viewKey):null;const next=await loadMessages(scope,saved?.anchor&&!saved.atBottom?{around:saved.anchor}:{});if(ticket!==epoch.current)return;setRows(next);setMore(next.length>=50);setHistory(!!saved?.anchor&&!saved.atBottom);setUnseen(false);if(saved?.anchor&&!saved.atBottom){pendingJump.current=saved.anchor;restoreOffset.current=saved.offset;nearBottom.current=false;follow.current=false;}else{nearBottom.current=true;follow.current=true;}}catch(e){if(ticket===epoch.current)setError(errorText(e));}finally{if(ticket===epoch.current)setLoading(false);}},[scope,viewKey]);
  useLayoutEffect(()=>{const el=transcript.current;return()=>rememberPosition(el,viewKey,nearBottom.current);},[viewKey]);
  useEffect(()=>{setRows([]);setSearch(false);void latest(true);return()=>{epoch.current++;};},[latest]);
  useEffect(()=>{const restored=connected&&!wasConnected.current;wasConnected.current=connected;if(!restored||loading)return;let valid=true;loadMessages(scope).then(next=>{if(!valid)return;if(history){setUnseen(true);return;}setRows(prev=>{const ids=new Set(prev.map(m=>m.id));return [...prev,...next.filter(m=>!ids.has(m.id))];});}).catch(e=>{if(valid)setError(errorText(e));});return()=>{valid=false;};},[connected,scope]);
  useEffect(()=>{if(incoming?.scope!==scope)return;const message=incoming.message;if(history){setUnseen(true);return;}setRows(prev=>prev.some(m=>m.id===message.id)?prev:[...prev,message]);if(!nearBottom.current)setUnseen(true);},[incoming,scope,history]);
  useEffect(()=>{const el=transcript.current;if(!el||loading)return;if(pendingJump.current){const target=el.querySelector<HTMLElement>(`[data-message-id="${CSS.escape(pendingJump.current)}"]`);if(restoreOffset.current!==null&&target){el.scrollTop+=target.getBoundingClientRect().top-el.getBoundingClientRect().top-restoreOffset.current;restoreOffset.current=null;}else{target?.scrollIntoView({block:'center'});target?.classList.add('gc-jump-highlight');}pendingJump.current='';return;}if(follow.current&&nearBottom.current)el.scrollTop=el.scrollHeight;},[rows,loading]);
  useEffect(()=>{markRead();});
  useEffect(()=>{const el=transcript.current;if(!el)return;const resize=new ResizeObserver(()=>{if(!el.getClientRects().length||!el.clientHeight)return;if(nearBottom.current&&follow.current)el.scrollTop=el.scrollHeight;setScrolled(el.scrollHeight-el.scrollTop-el.clientHeight>48);readNow.current();});resize.observe(el);return()=>resize.disconnect();},[]);
  useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(document.querySelector('dialog[open]'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='f'){e.preventDefault();setSearch(true);}};document.addEventListener('keydown',handler);return()=>document.removeEventListener('keydown',handler);},[]);
  const older=async()=>{if(busyOlder.current||!rows.length)return;busyOlder.current=true;const ticket=epoch.current,el=transcript.current!,height=el.scrollHeight,top=el.scrollTop;follow.current=false;try{const next=await loadMessages(scope,{before:rows[0].id});if(ticket!==epoch.current)return;setRows(prev=>[...next,...prev.filter(m=>!next.some(n=>n.id===m.id))]);setMore(next.length>=50);requestAnimationFrame(()=>{el.scrollTop=top+el.scrollHeight-height;});}catch(e){if(ticket===epoch.current)setError(errorText(e));}finally{busyOlder.current=false;}};
  const jump=async(id:string)=>{const ticket=epoch.current;let found=rows.find(m=>m.id===id);follow.current=false;nearBottom.current=false;if(!found){const next=await loadMessages(scope,{around:id});if(ticket!==epoch.current)return;found=next.find(m=>m.id===id);if(!found)throw Error('原消息已不可用。');setRows(next);setHistory(true);setMore(true);}pendingJump.current=id;await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));if(ticket!==epoch.current)return;const target=transcript.current?.querySelector<HTMLElement>(`[data-message-id="${CSS.escape(id)}"]`);target?.scrollIntoView({block:'center'});target?.classList.add('gc-jump-highlight');setTimeout(()=>target?.classList.remove('gc-jump-highlight'),1800);pendingJump.current='';};
  const author=(m:RoomMessage)=>m.sender==='user'?username:contacts.find(c=>c.id===m.senderMemberId)?.name??m.sender;
  const quote=(m:RoomMessage)=>{if(getDraft(scope).busy){onToast('请等待当前发送完成。');return;}if(!m.seq){onToast('这条历史消息暂时不能引用。');return;}const room=chat.kind==='room',current=room?contacts.filter(c=>memberIds.includes(c.id)):[],tag=room?quoteMention(m,username,current,true):undefined;updateDraft(scope,{quote:m,mentions:withQuoteMention(getDraft(scope).mentions,tag)});if(room&&!tag)onToast('已引用；无法确认作者仍在当前会话，未自动点名。');const input=document.getElementById('grDraft') as HTMLDivElement|null;input?.focus({preventScroll:true});};
  const sent=(s:string,m:RoomMessage)=>{if(s===scope){if(history)void latest();else{nearBottom.current=true;follow.current=true;setRows(prev=>prev.some(x=>x.id===m.id)?prev:[...prev,m]);}}onSent(s,m);};
  return <main className="gr-chat" id="grChat" onDragOver={e=>{if([...e.dataTransfer.types].includes('Files'))e.preventDefault();}} onDragEnter={e=>{if([...e.dataTransfer.types].includes('Files')&&!document.querySelector('dialog[open]')){e.preventDefault();dragDepth.current++;setDrag(true);}}} onDragLeave={()=>{if(--dragDepth.current<=0)setDrag(false);}} onDrop={e=>{if(![...e.dataTransfer.types].includes('Files'))return;e.preventDefault();dragDepth.current=0;setDrag(false);e.currentTarget.dispatchEvent(new CustomEvent('grok:files',{detail:[...e.dataTransfer.files]}));}}>
    <header className="gr-chat-header"><div className="gr-header-left"><IconButton className="gr-mobile-only" icon="layout-sidebar-left" label="打开会话列表" onClick={onNav}/><button className="gr-identity" aria-label={`查看 ${chat.title} 的资料`} onClick={()=>onPane('profile')}>{chat.kind==='room'?<GroupAvatar members={memberIds} size={24} username={username}/>:<Avatar id={chat.memberId??scope} size={22} status={connected?chat.status:'idle'} animated/>}<strong>{chat.title}</strong></button></div><div className="gr-header-actions"><IconButton icon="search" label="查找当前会话" onClick={()=>setSearch(v=>!v)}/><IconButton icon="pulse" label="活动" onClick={()=>onPane('activity')}/><IconButton icon="folder" label="资产" onClick={()=>onPane('assets')}/>{chat.kind==='room'&&<IconButton icon="people" label="查看群成员" onClick={()=>onPane('profile')}/>}</div></header>
    {search&&<Search key={scope} scope={scope} revision={rows.length} contacts={contacts.filter(c=>memberIds.includes(c.id)||c.id===chat.memberId)} username={username} onClose={()=>setSearch(false)} onJump={jump}/>}
    {(history||unseen||scrolled)&&<button className="gc-latest" onClick={()=>void latest()}><Icon name="arrow-up"/>{unseen?'有新消息 · ':''}回到最新</button>}
    <div className="gr-transcript" ref={transcript} tabIndex={-1} aria-label="聊天记录" onScroll={e=>{const el=e.currentTarget;if(!el.getClientRects().length||!el.clientHeight)return;nearBottom.current=el.scrollHeight-el.scrollTop-el.clientHeight<=4;setScrolled(el.scrollHeight-el.scrollTop-el.clientHeight>48);follow.current=nearBottom.current;if(!loading)rememberPosition(el,viewKey,nearBottom.current);if(nearBottom.current){setUnseen(false);markRead();}if(el.scrollTop<60&&more&&!loading)void older();}}>
      {loading&&<p className="gr-unloaded">正在加载聊天记录…</p>}{error&&<p className="gr-error" role="alert">{error} <button onClick={()=>void latest()}>重试</button></p>}{!loading&&more&&<button className="gr-load-older" onClick={()=>void older()}>加载更早消息</button>}{!loading&&!rows.length&&!error&&<p className="gr-unloaded">还没有消息，发一句开始吧。</p>}
      {rows.map((m,i)=>{const prev=rows[i-1],sameDay=prev&&new Date(prev.ts).toDateString()===new Date(m.ts).toDateString(),user=m.sender==='user',connected=!!prev&&sameDay&&prev.sender===m.sender&&prev.senderMemberId===m.senderMemberId&&m.ts-prev.ts<300000&&!m.type&&!prev.type;const files=(m.attachments??[]).map(a=>attachmentFile(scope,a));if(m.artifacts?.length&&chat.roomId)files.push(...m.artifacts.map(path=>({name:path.split('/').pop()||path,load:()=>getArtifactRawBlob(chat.roomId!,path)})));const referenced=rows.find(row=>row.id===m.replyTo?.messageId);return <Fragment key={m.id}>{!sameDay&&<div className="gr-date">{new Date(m.ts).toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric'})}</div>}{m.type||m.sender==='system'?<div className="gr-system-message" data-message-id={m.id}>{m.content}</div>:<>{chat.kind==='room'&&!user&&!connected&&<div className="gc-author"><Avatar id={m.senderMemberId??m.sender} size={20}/><span>{author(m)}</span></div>}<div className={`gr-message-row ${user?'gr-user':''} ${connected?'gr-connected':''}`} data-message-id={m.id} data-message={m.id} tabIndex={-1}><div className="gr-bubble gc-rich">{m.replyTo&&<button className="gc-reply" aria-label="回到引用原文" onClick={()=>void jump(m.replyTo!.messageId).catch(e=>onToast(errorText(e)))}><Icon name="arrow-u-up-right"/><span>{referenced?`${author(referenced)}：${referenced.content||'附件消息'}`:`#${m.replyTo.seq} · 查看原消息`}</span></button>}{m.content&&<Markdown text={m.content} mentions={['all',username,...contacts.map(c=>c.name),...m.mentions]}/>} {!!files.length&&<FileCards files={files} onOpen={onFile} onError={onToast}/>}<span className="gr-msg-actions"><IconButton icon="copy" label="复制这条消息" onClick={()=>void copyText(m.content).then(ok=>onToast(ok?'已复制':'未能复制，请选中文字手动复制'))}/><IconButton icon="chat-bubble" label="引用这条消息" onClick={()=>quote(m)}/></span></div></div></>}</Fragment>;})}
    </div>
    <Composer username={username} scope={scope} title={chat.title} contacts={contacts.filter(m=>memberIds.includes(m.id)||m.id===chat.memberId)} connected={connected} onSent={sent} onFile={onFile} onNeedRecipient={()=>{}}/>
    {drag&&<div className="ga-dropzone"><Icon name="paperclip"/><strong>松开，添加文件</strong><span>发送前可以预览</span></div>}
  </main>;
}
