import type {ConnectionRoute,ConnectionSettings} from '../api/client';
import {FormRow,SecretInput} from './EndpointFields';
import {IconButton,copyText} from './ui';
export function ConnectionFields({provider,route,name,setName,apiKey,setKey,settings,setSettings,busy,storedKey,advanced,setAdvanced,onNotice}:{provider:string;route:ConnectionRoute|'edit-name';name:string;setName:(value:string)=>void;apiKey:string;setKey:(value:string)=>void;settings:ConnectionSettings;setSettings:(value:ConnectionSettings)=>void;busy:boolean;storedKey:boolean;advanced:boolean;setAdvanced:(value:boolean)=>void;onNotice:(value:string)=>void}) {
 const keyField=['key','service','aws-token','vertex-key'].includes(route);
 const field=(key:Exclude<keyof ConnectionSettings,'mappings'>,id:string,label:string,placeholder='')=><FormRow id={id} label={label}><input id={id} className="ma-control" autoComplete="off" spellCheck={false} disabled={busy} value={settings[key]??''} placeholder={placeholder} onChange={event=>setSettings({...settings,[key]:event.target.value})}/></FormRow>;
 return <>
  <div className="gr-settings-card"><FormRow id="maAddName" label="接入名称"><input id="maAddName" className="ma-control" maxLength={80} autoComplete="off" value={name} disabled={busy} onChange={event=>setName(event.target.value)}/></FormRow>
   {keyField&&<SecretInput label={route==='aws-token'?'Bearer Token':route==='vertex-key'?'Google Cloud API Key':'API Key'} value={apiKey} onChange={setKey} disabled={busy} stored={storedKey}/>}
   {route==='service'&&(provider==='cloudflare-ai-gateway'||provider==='cloudflare-workers-ai')&&<>{field('account','maAccountId','账号 ID','Cloudflare 账号 ID')}{provider==='cloudflare-ai-gateway'&&field('gateway','maGatewayId','网关 ID','AI Gateway ID')}</>}
   {route==='service'&&provider==='azure-openai-responses'&&<><FormRow id="maAzureMode" label="地址方式"><select id="maAzureMode" className="ma-control" disabled={busy} value={settings.azureMode??'url'} onChange={event=>setSettings({...settings,azureMode:event.target.value as 'url'|'resource'})}><option value="url">基础 URL</option><option value="resource">资源名</option></select></FormRow>{settings.azureMode==='resource'?field('resource','maResource','资源名','my-resource'):field('baseUrl','maBaseUrl','基础 URL','https://example.openai.azure.com/openai/v1')}</>}
   {route==='aws-profile'&&field('profile','maProfile','AWS profile','default')}
   {(route==='vertex-adc'||route==='vertex-file')&&<>{field('project','maProject','项目 ID','my-project')}{field('location','maLocation','地区','us-central1')}{route==='vertex-file'&&field('path','maCredentialPath','凭证文件','服务端的文件路径')}</>}
   {route==='edit-name'&&<div className="gr-setting-row ma-method-fact"><span>接入方式</span><span>账号授权</span></div>}
  </div>
  {route==='service'&&provider==='azure-openai-responses'&&<details className="ma-flow-details" id="maServiceAdvanced" open={advanced} onToggle={event=>setAdvanced(event.currentTarget.open)}><summary>高级配置</summary><div className="gr-settings-card">{field('apiVersion','maApiVersion','API 版本','使用默认值')}</div><div className="ma-map-section"><p className="ma-note">部署映射 · 留空时使用模型 ID</p>{(settings.mappings??[]).map((mapping,index)=><div className="ma-map-row" key={index}><input className="ma-control" aria-label={`第${index+1}项模型 ID`} placeholder="模型 ID" value={mapping.model} disabled={busy} onChange={event=>setSettings({...settings,mappings:settings.mappings!.map((item,i)=>i===index?{...item,model:event.target.value}:item)})}/><span aria-hidden="true">→</span><input className="ma-control" aria-label={`第${index+1}项部署名`} placeholder="部署名" value={mapping.deployment} disabled={busy} onChange={event=>setSettings({...settings,mappings:settings.mappings!.map((item,i)=>i===index?{...item,deployment:event.target.value}:item)})}/><IconButton icon="close" label={`移除第${index+1}项部署映射`} disabled={busy} onClick={()=>setSettings({...settings,mappings:settings.mappings!.filter((_,i)=>i!==index)})}/></div>)}<button className="gr-button" type="button" disabled={busy} onClick={()=>setSettings({...settings,mappings:[...(settings.mappings??[]),{model:'',deployment:''}]})}>添加部署映射</button></div></details>}
  {route==='aws-profile'&&<p className="ma-note">使用运行 Bossmode 服务的机器上已有的 AWS profile。</p>}
  {route==='aws-chain'&&<p className="ma-note">使用运行 Bossmode 服务的机器上已有的 AWS 凭证，包括 IAM、容器或角色凭证。</p>}
  {route==='vertex-file'&&<p className="ma-note">填写服务所在机器上的凭证文件位置，不是从当前电脑上传文件。</p>}
  {route==='vertex-adc'&&<><p className="ma-note">先在运行 Bossmode 服务的机器上配置应用默认凭证。</p><div className="ma-command"><code>gcloud auth application-default login</code><button type="button" className="gr-button" onClick={()=>void copyText('gcloud auth application-default login').then(ok=>onNotice(ok?'已复制命令':'未能复制，请手动复制'))}>复制命令</button></div></>}
 </>;
}
