import {useState,type Dispatch,type ReactNode,type SetStateAction} from 'react';
import {IconButton} from './ui';
import {endpointProtocols,thinkingFormats,thinkingLevels,priceKeys,type EndpointDraft} from './model-form';

export function FormRow({id,label,children}:{id:string;label:string;children:ReactNode}) {return <div className="gr-setting-row ma-entry-row"><label htmlFor={id}>{label}</label>{children}</div>;}
export function SecretInput({id='maAddKey',label='API Key',value,onChange,stored=false,disabled=false}:{id?:string;label?:string;value:string;onChange:(value:string)=>void;stored?:boolean;disabled?:boolean}) {
 const [visible,setVisible]=useState(false);
 return <FormRow id={id} label={label}><div className="ma-secret"><input id={id} className="ma-control" type={visible?'text':'password'} autoComplete="off" spellCheck={false} value={value} placeholder={stored?'已配置，留空不变':''} onChange={event=>onChange(event.target.value)} disabled={disabled}/><button type="button" aria-controls={id} aria-pressed={visible} aria-label={`${visible?'隐藏':'显示'}${label}`} disabled={disabled} onClick={()=>setVisible(v=>!v)}>{visible?'隐藏':'显示'}</button></div></FormRow>;
}
export function EndpointFields({draft,setDraft,busy,storedKey,advanced,setAdvanced}:{draft:EndpointDraft;setDraft:Dispatch<SetStateAction<EndpointDraft>>;busy:boolean;storedKey:boolean;advanced:boolean;setAdvanced:(value:boolean)=>void}) {
 const field=(key:'url'|'modelId'|'displayName'|'context'|'output',id:string,label:string,placeholder='')=><FormRow id={id} label={label}><input id={id} className="ma-control" autoComplete="off" spellCheck={false} value={draft[key]} placeholder={placeholder} disabled={busy} onChange={event=>setDraft(d=>({...d,[key]:event.target.value}))}/></FormRow>;
 const focus=(id:string)=>requestAnimationFrame(()=>{document.getElementById(id)?.focus({preventScroll:true});document.getElementById(id)?.scrollIntoView({block:'nearest'});});
 return <>
  <div className="gr-settings-card">{field('url','maEpUrl','API URL','https://api.example.com/v1')}<SecretInput value={draft.key} onChange={key=>setDraft(d=>({...d,key}))} stored={storedKey} disabled={busy}/>{field('modelId','maEpModel','模型名','例如 model-id')}</div>
  <div className="ma-ep-auto"><button className="gr-button" type="button" disabled aria-describedby="maEpAutoNote">自动配置</button><span id="maEpAutoNote">尚未接入</span></div>
  <section className="ma-ep-section"><h2>基础配置</h2><div className="gr-settings-card">{field('displayName','maEpDisplay','显示名','同模型名')}<FormRow id="maEpApi" label="协议"><select id="maEpApi" className="ma-control" value={draft.protocol} disabled={busy} onChange={event=>setDraft(d=>({...d,protocol:event.target.value as EndpointDraft['protocol']}))}>{(endpointProtocols.includes(draft.protocol)?endpointProtocols:[draft.protocol,...endpointProtocols]).map(api=><option key={api}>{api}</option>)}</select></FormRow><div className="ma-ep-numbers">{[['context','maEpContext','上下文窗口'],['output','maEpOutput','最大输出']].map(([key,id,label])=><div key={key}><label htmlFor={id}>{label}</label><input id={id} className="ma-control" inputMode="numeric" autoComplete="off" placeholder="未填写" value={draft[key as 'context'|'output']} disabled={busy} onChange={event=>setDraft(d=>({...d,[key]:event.target.value}))}/></div>)}</div></div></section>
  <details className="ma-flow-details ma-ep-advanced" id="maEpAdvanced" open={advanced} onToggle={event=>setAdvanced(event.currentTarget.open)}><summary>高级配置</summary>
   <div className="gr-settings-card"><div className="gr-setting-row ma-entry-row"><span id="maEpReasonLabel">支持思考</span><button type="button" className="gr-switch" id="maEpReason" role="switch" aria-checked={draft.reasoning} aria-labelledby="maEpReasonLabel" disabled={busy} onClick={()=>setDraft(d=>({...d,reasoning:!d.reasoning}))}/></div><FormRow id="maEpFormat" label="思考格式"><select id="maEpFormat" className="ma-control" disabled={busy||!draft.reasoning||draft.protocol!=='openai-completions'} value={draft.format} onChange={event=>setDraft(d=>({...d,format:event.target.value}))}><option value="">继承</option>{thinkingFormats.map(format=><option key={format}>{format}</option>)}</select></FormRow></div>
   {!!draft.format&&draft.protocol!=='openai-completions'&&<p className="ma-note">已保留思考格式；当前协议不使用这项配置。</p>}{!draft.reasoning&&(draft.format||thinkingLevels.some(level=>draft.levels[level].mode!=='inherit'))&&<p className="ma-note">已保留思考配置，开启“支持思考”后使用。</p>}
   <section className="ma-ep-section"><h3>计价 <span>美元／百万 token</span></h3><div className="gr-settings-card ma-ep-prices">{priceKeys.map(key=><div key={key}><label htmlFor={`maEpPrice-${key}`}>{{input:'输入',output:'输出',cacheRead:'缓存读取',cacheWrite:'缓存写入'}[key]}</label><input id={`maEpPrice-${key}`} className="ma-control" inputMode="decimal" autoComplete="off" placeholder="未知" value={draft.prices[key]} disabled={busy} onChange={event=>setDraft(d=>({...d,prices:{...d.prices,[key]:event.target.value}}))}/></div>)}</div></section>
   <section className="ma-ep-section"><h3>思考档映射</h3><div className="gr-settings-card">{thinkingLevels.map(level=><div className="gr-setting-row ma-entry-row ma-ep-map" key={level}><label htmlFor={`maEpMap-${level}`}>{level}</label><div className="ma-ep-map-control"><select id={`maEpMap-${level}`} className="ma-control" disabled={!draft.reasoning||busy} value={draft.levels[level].mode} onChange={event=>setDraft(d=>({...d,levels:{...d.levels,[level]:{...d.levels[level],mode:event.target.value as 'inherit'|'unsupported'|'value'}}}))}><option value="inherit">继承</option><option value="unsupported">不支持</option><option value="value">指定值</option></select>{draft.levels[level].mode==='value'&&<input id={`maEpValue-${level}`} aria-label={`${level} 指定值`} className="ma-control" maxLength={80} autoComplete="off" placeholder="发送值" value={draft.levels[level].value} disabled={!draft.reasoning||busy} onChange={event=>setDraft(d=>({...d,levels:{...d.levels,[level]:{...d.levels[level],value:event.target.value}}}))}/>}</div></div>)}</div><p className="ma-note">继承时省略此项；xhigh 和 max 继承时不支持。</p></section>
   <section className="ma-ep-section"><h3>自定义请求头</h3>{draft.headers.map((row,index)=><div className="ma-map-row ma-ep-header" key={index}><input id={`maEpHeader-${index}`} className="ma-control" maxLength={120} aria-label={`第${index+1}项请求头名称`} placeholder="名称" autoComplete="off" value={row.name} disabled={busy} onChange={event=>setDraft(d=>({...d,headers:d.headers.map((header,i)=>i===index?{...header,name:event.target.value,stored:false}:header)}))}/><input id={`maEpHeaderValue-${index}`} className="ma-control" type="password" aria-label={`第${index+1}项请求头值`} autoComplete="off" placeholder={row.stored?'已配置，留空不变':'值'} value={row.value} disabled={busy} onChange={event=>setDraft(d=>({...d,headers:d.headers.map((header,i)=>i===index?{...header,value:event.target.value}:header)}))}/><IconButton icon="close" label={`移除第${index+1}项请求头`} disabled={busy} onClick={()=>{setDraft(d=>({...d,headers:d.headers.filter((_,i)=>i!==index)}));focus('maEpAddHeader');}}/></div>)}<button id="maEpAddHeader" type="button" className="gr-button" disabled={busy} onClick={()=>{const index=draft.headers.length;setDraft(d=>({...d,headers:[...d.headers,{name:'',value:''}]}));focus(`maEpHeader-${index}`);}}>添加请求头</button></section>
  </details>
 </>;
}
