import { renderToStaticMarkup } from "react-dom/server";
import { resolveFileLink } from "./file-links";
import { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { apiFetchBlob, type RoomMessageAttachment } from '../api/client';
import { attachmentBlob } from './api';
import { Icon, IconButton, Markdown, bytes, errorText } from './ui';
export interface ViewFile {id?:string;path?:string;name:string;content?:string;url?:string;mimeType?:string;size?:number;blob?:Blob;load?:()=>Promise<Blob>;download?:()=>void}
export const attachmentFile=(scope:string,a:RoomMessageAttachment):ViewFile=>({id:a.storedFilename,name:a.originalFilename,mimeType:a.mime,size:a.size,load:()=>attachmentBlob(scope,a.storedFilename)});
export function fileKind(file:ViewFile) {const ext=file.name.split('.').pop()?.toLowerCase()??'';if(file.mimeType?.startsWith('image/')||['png','jpg','jpeg','gif','webp','svg','avif'].includes(ext))return 'image';if(['html','htm'].includes(ext)||file.mimeType==='text/html')return 'html';if(['md','markdown'].includes(ext))return 'markdown';if(file.mimeType?.startsWith('text/')||['txt','json','jsonl','yaml','yml','ts','tsx','js','jsx','css','log','csv','py','sh','sql','toml','xml'].includes(ext))return 'text';return 'download';}
export async function loadFile(file:ViewFile) {
  if(file.blob)return file.blob;
  if(file.content!=null)return new Blob([file.content],{type:file.mimeType||'text/plain'});
  if(file.load)return file.load();
  if(file.url){const target=new URL(file.url,location.href);if(target.protocol==='blob:')return (await fetch(target)).blob();if(target.origin!==location.origin||!target.pathname.startsWith('/api/'))throw Error('文件地址不属于当前服务');return apiFetchBlob(target.pathname+target.search);}
  throw Error('文件没有可读取的内容');
}
export async function downloadFile(file:ViewFile) {if(file.download){file.download();return;}const blob=await loadFile(file),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=file.name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
function Thumbnail({file}: {file:ViewFile}) {const [url,setUrl]=useState('');useEffect(()=>{let alive=true,current='';loadFile(file).then(blob=>{if(alive){current=URL.createObjectURL(blob);setUrl(current);}}).catch(()=>{});return()=>{alive=false;if(current)URL.revokeObjectURL(current);};},[file.id,file.name,file.url]);return url?<img src={url} alt={file.name} loading="lazy"/>:<Icon name="image"/>;}
export function FileCards({files,onOpen,onError}: {files:ViewFile[];onOpen:(files:ViewFile[],index:number)=>void;onError:(message:string)=>void}) {return <div className={`ga-message-files ${files.some(f=>fileKind(f)==='image')?'ga-has-images':''}`}>{files.map((f,i)=><div key={`${f.name}-${i}`} className={`ga-message-file ${fileKind(f)==='image'?'ga-message-image':''}`}><button className="ga-message-open" onClick={()=>onOpen(files,i)} aria-label={`预览 ${f.name}`}>{fileKind(f)==='image'?<span className="ga-image-frame"><Thumbnail file={f}/></span>:<span className="ga-file-icon"><Icon name="file"/></span>}<span className="ga-file-copy"><strong title={f.name}>{f.name}</strong><small>{f.name.split('.').pop()?.toUpperCase()} {f.size!=null&&`· ${bytes(f.size)}`}</small></span></button><IconButton icon="cloud-download" label={`下载 ${f.name}`} onClick={()=>void downloadFile(f).catch(e=>onError(errorText(e)))}/></div>)}</div>;}
// The renderer is isolated even when the uploaded document contains scripts or network URLs.
function safeHtml(text:string) {const parsed=new DOMParser().parseFromString(text,'text/html');parsed.querySelectorAll('script,iframe,frame,object,embed,link,meta,base,audio,video,source,track').forEach(el=>el.remove());parsed.querySelectorAll('*').forEach(el=>{for(const a of [...el.attributes]){if(a.name.startsWith('on')||['href','xlink:href','srcset','action','formaction','target','autofocus','contenteditable'].includes(a.name)||(a.name==='src'&&!a.value.startsWith('data:image/')))el.removeAttribute(a.name);}if(['BUTTON','INPUT','SELECT','TEXTAREA'].includes(el.tagName))el.setAttribute('disabled','');});return `<!doctype html><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src data:; form-action 'none'; base-uri 'none'"><meta charset="utf-8">${parsed.documentElement.outerHTML}`;}
export function FileViewer({files,initialIndex=0,onClose}:{files:ViewFile[];initialIndex?:number;onClose:()=>void}) {
  const [index,setIndex]=useState(initialIndex),[mode,setMode]=useState<'preview'|'source'>('preview'),[wide,setWide]=useState(false),[blob,setBlob]=useState<Blob|null>(null),[url,setUrl]=useState(''),[text,setText]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[notice,setNotice]=useState('');
  const ref=useRef<HTMLDialogElement>(null),body=useRef<HTMLDivElement>(null),positions=useRef(new Map<string,number>()),pendingAnchor=useRef(''); const f=files[index],kind=fileKind(f);
  useEffect(()=>{const el=ref.current!,prev=document.activeElement as HTMLElement|null;el.showModal();return()=>{el.close();if(prev?.isConnected)prev.focus({preventScroll:true});};},[]);
  useEffect(()=>{let alive=true,objectUrl='';setBlob(null);setText('');setError('');setLoading(true);setMode('preview');loadFile(f).then(async data=>{if(!alive)return;setBlob(data);objectUrl=URL.createObjectURL(data);setUrl(objectUrl);if(data.size<=1024*1024&&kind!=='image'){const s=await data.text();if(alive)setText(s);}if(alive)setLoading(false);}).catch(e=>{if(alive){setError(errorText(e));setLoading(false);}});return()=>{alive=false;if(objectUrl)URL.revokeObjectURL(objectUrl);};},[f]);
  useEffect(()=>{if(body.current)body.current.scrollTop=positions.current.get(`${index}:${mode}`)??0;},[index,mode,loading]);
  const choose=(next:number)=>{setNotice('');if(next!==index)setLoading(true);positions.current.set(`${index}:${mode}`,body.current?.scrollTop??0);setIndex(Math.max(0,Math.min(files.length-1,next)));};
  const toggle=()=>{positions.current.set(`${index}:${mode}`,body.current?.scrollTop??0);setMode(m=>m==='preview'?'source':'preview');};
  const anchor=(hash:string)=>{const wanted=hash.toLocaleLowerCase();const headings=[...body.current?.querySelectorAll<HTMLElement>('h1,h2,h3,h4,h5,h6')??[]];const target=headings.find(el=>el.id===hash||el.textContent?.trim().toLocaleLowerCase().replace(/\s+/g,'-')===wanted);if(target){target.scrollIntoView({block:'start'});target.tabIndex=-1;target.focus({preventScroll:true});}else setNotice('这篇文档里没有找到该位置。');};
  useEffect(()=>{if(!loading&&pendingAnchor.current){const hash=pendingAnchor.current;pendingAnchor.current='';requestAnimationFrame(()=>anchor(hash));}},[loading,text,index]);
  const link=(href:string)=>{if(/^(https?:\/\/|mailto:)/i.test(href)){window.open(href,'_blank','noopener,noreferrer');return;}const target=resolveFileLink(files,index,href);if(!target){setNotice('没有找到对应文件，或存在同名文件。');return;}if(target.index===index){anchor(target.hash);return;}pendingAnchor.current=target.hash;choose(target.index);};
  const toggleWide=()=>{const el=body.current,bounds=el?.getBoundingClientRect(),blocks=[...el?.querySelectorAll<HTMLElement>('.gd-prose>*')??[]],index=blocks.findIndex(block=>block.getBoundingClientRect().bottom>(bounds?.top??0)),anchor=index>=0?blocks[index]:null,offset=anchor&&bounds?anchor.getBoundingClientRect().top-bounds.top:0;setWide(value=>!value);requestAnimationFrame(()=>{if(el&&anchor?.isConnected)el.scrollTop+=anchor.getBoundingClientRect().top-el.getBoundingClientRect().top-offset;});};
  const openTab=()=>{if(!blob)return;const win=window.open('about:blank','_blank');if(!win){setNotice('新标签被浏览器拦截，请允许后再试。');return;}win.opener=null;let imageUrl='';let content:Blob;if(kind==='image'){imageUrl=URL.createObjectURL(blob);content=new Blob([`<!doctype html><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src blob:; style-src 'unsafe-inline'"><style>body{margin:24px;text-align:center}img{max-width:100%}</style><img src="${imageUrl}">`],{type:'text/html'});}else if(kind==='html')content=new Blob([safeHtml(text)],{type:'text/html'});else if(kind==='markdown'){const html=safeHtml(body.current?.querySelector('.gd-prose')?.innerHTML??renderToStaticMarkup(<Markdown text={text}/>));content=new Blob([html+'<style>body{font:14px/1.75 system-ui;max-width:800px;margin:32px auto;padding:0 24px}pre{padding:16px;background:#f4f4f4;overflow:auto}table{border-collapse:collapse}td,th{border:1px solid #ddd;padding:8px}button{display:none}</style>'],{type:'text/html'});}else content=new Blob([text],{type:'text/plain'});const objectUrl=URL.createObjectURL(content);win.location.replace(objectUrl);setTimeout(()=>{URL.revokeObjectURL(objectUrl);if(imageUrl)URL.revokeObjectURL(imageUrl);},60000);};
  return createPortal(<dialog ref={ref} className="ga-viewer" aria-labelledby="gaPreviewTitle" data-wide={wide?'':undefined} onCancel={e=>{e.preventDefault();onClose();}} onKeyDown={e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)&&!['SELECT','INPUT','TEXTAREA','PRE'].includes((e.target as HTMLElement).tagName)){e.preventDefault();choose(index+(e.key==='ArrowLeft'?-1:1));}}}><header className="ga-preview-header"><div className="ga-preview-heading"><h1 id="gaPreviewTitle">{f.name}</h1><small>{kind.toUpperCase()} · {bytes(blob?.size??f.size)}</small></div><div className="ga-preview-actions">{['markdown','html','text'].includes(kind)&&blob&&blob.size<=1024*1024&&<button className="gr-button" onClick={toggle}>{mode==='source'?'预览':kind==='html'?'源码':'原文'}</button>}<IconButton icon="cloud-download" label={`下载 ${f.name}`} onClick={()=>void downloadFile(f).catch(e=>setError(errorText(e)))}/>{blob&&blob.size<=1024*1024&&kind!=='download'&&<IconButton icon="window" label="在新标签打开预览" onClick={openTab}/>}<IconButton icon={wide?'arrows-contract':'arrows-expand'} label={wide?'收起预览':'扩大预览'} onClick={toggleWide}/><IconButton icon="close" label="关闭附件预览" onClick={onClose}/></div></header><div className={`ga-preview-body ${kind==='image'?'ga-image-view':kind==='html'&&mode==='preview'?'ga-html-view':kind==='markdown'&&mode==='preview'?'gd-document':''}`} ref={body}>
    {notice&&<p className="gd-notice" role="status">{notice}</p>}{loading?<p className="gr-unloaded">正在读取文件…</p>:error?<p className="gr-error" role="alert">{error}</p>:kind==='image'?<img className="ga-preview-image" src={url} alt={f.name}/>:kind==='download'||(blob?.size??0)>1024*1024?<div className="ga-fallback"><Icon name="file"/><strong>此文件请下载后查看</strong><p>文件类型或大小不适合在页面内预览。</p><button className="gr-button" onClick={()=>void downloadFile(f).catch(e=>setError(errorText(e)))}>下载文件</button></div>:mode==='source'||kind==='text'?<pre className="ga-source" tabIndex={0}>{text}</pre>:kind==='html'?<iframe title={f.name} sandbox="" srcDoc={safeHtml(text)} referrerPolicy="no-referrer" className="ga-html-frame"/>:<article className="gd-prose"><Markdown text={text} onLink={link}/></article>}
  </div>{files.length>1&&<footer className="ga-preview-nav"><IconButton icon="chevron-left" label="上一个附件" disabled={index===0} onClick={()=>choose(index-1)}/><select id="gaPreviewSelect" aria-label="选择预览文件" value={index} onChange={e=>choose(Number(e.target.value))}>{files.map((f,i)=><option key={i} value={i}>{f.name}</option>)}</select><span>{index+1} / {files.length}</span><IconButton icon="chevron-right" label="下一个附件" disabled={index===files.length-1} onClick={()=>choose(index+1)}/></footer>}</dialog>,document.body);
}
