import {useEffect,useState} from 'react';
import {getAvailableModels,patchGlobalMember,type AvailableModelOption,type MemberDetail} from '../api/client';
import {availableThinkingLevels,findModelOptionForBinding} from '../components/thinking-levels';
import {Icon,Menu,MenuItem,errorText} from './ui';
const labels:Record<string,string>={default:'默认',off:'关闭',minimal:'最低',low:'低',medium:'中',high:'高',xhigh:'极高',max:'最高'};
export function MemberConfigFields({member,onSaved}:{member:MemberDetail;onSaved:(member:MemberDetail)=>void}) {
  const [models,setModels]=useState<AvailableModelOption[]>([]),[menu,setMenu]=useState<{kind:'model'|'thinking';x:number;y:number;width:number}|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{let active=true;getAvailableModels().then(m=>{if(active)setModels(m);}).catch(e=>{if(active)setError(errorText(e));});return()=>{active=false;};},[member.memberId]);
  const current=findModelOptionForBinding(member.global?.model,member.global?.credentialId,models),modelName=current?(current.displayName||current.modelId)+(models.filter(m=>(m.displayName||m.modelId)===(current.displayName||current.modelId)).length>1?` · ${current.profileName}`:''):member.global?.model?member.global.model+' · 不可用':'未选择',thinking=member.global?.thinkingLevel??'default';
  const save=async(patch:Record<string,unknown>)=>{if(busy)return;setMenu(null);setBusy(true);setError('');try{const r=await patchGlobalMember(member.memberId,patch);onSaved(r.member);}catch(e){setError(errorText(e));}finally{setBusy(false);}};
  const field=(kind:'model'|'thinking',title:string,text:string)=><div className="gr-field"><span className="gp-field-label">{title}</span><button className="gp-field-value gp-config-select" aria-label={`${title}：${text}`} aria-haspopup="menu" aria-expanded={menu?.kind===kind} disabled={busy} onClick={e=>{const r=e.currentTarget.getBoundingClientRect();setMenu({kind,x:r.left,y:r.bottom+6,width:Math.max(250,r.width)});}}><span>{text}</span><Icon name="chevron-down"/></button></div>;
  return <div className="gp-model-config">{field('model','模型',modelName)}{current?.reasoning&&field('thinking','思考强度',labels[thinking]??thinking)}{error&&<p className="gp-config-error" role="alert">{error}</p>}{menu&&<Menu x={menu.x} y={menu.y} width={menu.width} label={menu.kind==='model'?'选择模型':'思考强度'} onClose={()=>setMenu(null)}>{menu.kind==='model'?models.length?models.map(m=><MenuItem key={m.profileId+'|'+m.ref} role="menuitemradio" aria-checked={current?.profileId===m.profileId&&current.ref===m.ref} onClick={()=>void save({model:m.ref,credentialId:m.profileId})}>{m.displayName||m.modelId}<small className="gr-small"> · {m.profileName}</small></MenuItem>):<p className="gp-model-menu-note">没有可选模型；请在设置的「模型」中添加接入。</p>:availableThinkingLevels(current).map(level=><MenuItem key={level.label} role="menuitemradio" aria-checked={(member.global?.thinkingLevel??null)===level.value} onClick={()=>void save({thinkingLevel:level.value})}>{labels[level.label]??level.label}</MenuItem>)}</Menu>}</div>;
}
