import {AuthFields} from './AuthFields';
import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import * as api from '../api/client';
import {Icon,IconButton,errorText} from './ui';
import {ProviderIcon} from './ProviderIcon';
import {ConnectionFields} from './ConnectionFields';
import {EndpointFields} from './EndpointFields';
import {endpointDraft,serializeEndpoint,validateHeaderDrafts,FormError,type EndpointDraft} from './model-form';

type Step='picker'|'methods'|'cloud-methods'|'auth'|'edit-name'|'endpoint'|api.ConnectionRoute;
const terminal=(job:api.OAuthLoginJob|null)=>!job||['completed','cancelled','failed'].includes(job.status);
const serviceProviders=['azure-openai-responses','cloudflare-ai-gateway','cloudflare-workers-ai'];
export function ModelConnectionDialog({existing,reconnect=false,modelIndex=0,profileNames=[],onClose,onSaved,onDirty}:{existing?:api.PublicModelCredentialProfile;reconnect?:boolean;modelIndex?:number;profileNames?:string[];onClose:()=>void;onSaved:(profile:api.PublicModelCredentialProfile)=>void;onDirty:(dirty:boolean)=>void}) {
 const account=!!existing&&(existing.authType==='oauth'||!!existing.oauthProviderId),initialStep:Step=!existing?'picker':existing.profileKind==='custom_endpoint'?'endpoint':account?reconnect?'auth':'edit-name':existing.connection?.route??(serviceProviders.includes(existing.providerSlug)?'service':'key');
 const [step,setStep]=useState<Step>(initialStep),[provider,setProvider]=useState(existing?.providerSlug??''),[providers,setProviders]=useState<api.PublicModelProvider[]>([]),[providerError,setProviderError]=useState(''),[providerLoading,setProviderLoading]=useState(true),[providerRetry,setProviderRetry]=useState(0),[search,setSearch]=useState(''),[name,setName]=useState(existing?.name??''),[key,setKey]=useState(''),[settings,setSettings]=useState<api.ConnectionSettings>(existing?.connection?.settings??(existing?.providerSlug==='azure-openai-responses'?{azureMode:'url'}:{})),[endpoint,setEndpoint]=useState(()=>endpointDraft(existing,modelIndex)),[advanced,setAdvanced]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[guard,setGuard]=useState<null|'close'|'back'>(null),[job,setJob]=useState<api.OAuthLoginJob|null>(null),[code,setCode]=useState(''),[readRetry,setReadRetry]=useState(0);
 const dialog=useRef<HTMLDialogElement>(null),flow=useRef<HTMLDivElement>(null),picker=useRef<HTMLDivElement>(null),alive=useRef(true),stack=useRef<Step[]>([]),pickerPosition=useRef(0),pickerFocus=useRef<HTMLElement|null>(null),pendingFocus=useRef<HTMLElement|null>(null),jobRef=useRef(job),nameRef=useRef(name),generation=useRef(0),autoStarted=useRef(false),completed=useRef(''),slug=useRef(`custom-${crypto.getRandomValues(new Uint32Array(1))[0].toString(16)}`);
 jobRef.current=job;nameRef.current=name;
 const baseline=useRef(JSON.stringify({name:existing?.name??'',key:'',settings:existing?.connection?.settings??(existing?.providerSlug==='azure-openai-responses'?{azureMode:'url'}:{}),endpoint:endpointDraft(existing,modelIndex)}));
 const dirty=JSON.stringify({name,key,settings,endpoint})!==baseline.current,activeAuth=!terminal(job),selected=providers.find(p=>p.providerSlug===provider);
 const title=step==='picker'?'添加模型':step==='endpoint'?'自定义端点':selected?.displayName??existing?.name??provider;
 useEffect(()=>{alive.current=true;const el=dialog.current!,previous=document.activeElement as HTMLElement|null;el.showModal();return()=>{alive.current=false;generation.current++;el.close();onDirty(false);if(previous?.isConnected)previous.focus({preventScroll:true});};},[]);
 useEffect(()=>{let active=true;setProviderLoading(true);setProviderError('');api.getModelProviderCatalog().then(data=>{if(active)setProviders(data);}).catch(e=>{if(active)setProviderError(errorText(e));}).finally(()=>{if(active)setProviderLoading(false);});return()=>{active=false;};},[providerRetry]);
 useEffect(()=>{onDirty(dirty||activeAuth);},[dirty,activeAuth]);
 useEffect(()=>{setError('');setNotice('');setCode('');if(step==='picker'){if(picker.current)picker.current.scrollTop=pickerPosition.current;(pickerFocus.current?.isConnected?pickerFocus.current:document.getElementById('maProviderSearch'))?.focus({preventScroll:true});}else{if(flow.current)flow.current.scrollTop=0;document.getElementById('maAddTitle')?.focus({preventScroll:true});}},[step]);
 useEffect(()=>{if(guard){pendingFocus.current??=document.activeElement as HTMLElement;document.getElementById('maContinueEdit')?.focus();}else if(pendingFocus.current?.isConnected){pendingFocus.current.focus({preventScroll:true});pendingFocus.current=null;}},[guard]);
 const showError=(value:unknown)=>{setError(errorText(value));if(value instanceof FormError){if(value.field.startsWith('maEpPrice')||value.field.startsWith('maEpValue')||value.field.startsWith('maEpHeader'))setAdvanced(true);requestAnimationFrame(()=>{const input=document.getElementById(value.field);input?.setAttribute('aria-invalid','true');input?.focus();input?.scrollIntoView({block:'nearest'});});}};
 const beginOAuth=async()=>{
  if(busy)return;if(!name.trim()){showError(new FormError('maAuthName','请填写接入名称。'));return;}const previousJob=jobRef.current;setBusy(true);setError('');setCode('');setNotice('');setJob(null);const epoch=++generation.current;
  try{if(!terminal(previousJob))await api.cancelOAuthConnection(previousJob!.id);const next=await api.startOAuthConnection({providerId:provider,profileId:existing?.id,name:name.trim()||selected?.displayName||provider});if(alive.current&&epoch===generation.current)setJob(next);}catch(e){if(alive.current&&epoch===generation.current)showError(e);}finally{if(alive.current&&epoch===generation.current)setBusy(false);}
 };
 useEffect(()=>{if(initialStep==='auth'&&!autoStarted.current){autoStarted.current=true;void beginOAuth();}},[]);
 useEffect(()=>{if(!job||terminal(job))return;let active=true,timer:ReturnType<typeof setTimeout>;const epoch=generation.current;const poll=async()=>{try{const next=await api.getOAuthConnectionJob(job.id);if(active&&epoch===generation.current){setJob(next);setError(previous=>previous.startsWith('读取授权状态失败：')?'':previous);}}catch(e){if(active&&epoch===generation.current)setError(`读取授权状态失败：${errorText(e)}`);}finally{if(active&&epoch===generation.current)timer=setTimeout(poll,1000);}};timer=setTimeout(poll,750);return()=>{active=false;clearTimeout(timer);};},[job?.id,job?.status]);
 useEffect(()=>{if(job?.status!=='completed'||completed.current===job.id)return;let active=true;setBusy(true);api.getModelCredentialProfiles().then(async profiles=>{if(!active)return;let profile=profiles.find(p=>p.id===job.profileId);if(!profile)throw Error('暂未读到已保存的接入。');const targetName=nameRef.current.trim();if(!targetName)throw new FormError('maAuthName','请填写接入名称。');if(profile.name!==targetName)profile=await api.updateModelCredentialProfile(profile.id,{name:targetName});if(!active)return;completed.current=job.id;setKey('');setCode('');onSaved(profile);}).catch(e=>{if(active)setError(`授权已完成，但接入尚未确认：${errorText(e)}`);}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[job?.status,job?.profileId,readRetry]);
 const resetDraft=()=>{const original=JSON.parse(baseline.current);setName(original.name);setKey('');setSettings(original.settings);setEndpoint(original.endpoint);setAdvanced(false);setError('');};
 const leave=async(action:'close'|'back',confirmed=false)=>{if(busy)return;if(!confirmed&&(dirty||activeAuth)){pendingFocus.current=document.activeElement as HTMLElement;setGuard(action);return;}setBusy(true);setError('');generation.current++;try{if(!terminal(jobRef.current))await api.cancelOAuthConnection(jobRef.current!.id);setJob(null);setCode('');setKey('');setGuard(null);if(action==='close'){onClose();return;}resetDraft();setStep(stack.current.pop()??'picker');}catch(e){showError(e);}finally{if(alive.current)setBusy(false);}};
 const chooseProvider=(id:string)=>{pickerPosition.current=picker.current?.scrollTop??0;pickerFocus.current=document.activeElement as HTMLElement;const info=providers.find(p=>p.providerSlug===id);let nextName=info?.displayName??'';const originalName=nextName;let suffix=2;while(profileNames.includes(nextName))nextName=`${originalName} ${suffix++}`;const nextSettings:api.ConnectionSettings=id==='azure-openai-responses'?{azureMode:'url'}:{},nextEndpoint=endpointDraft();setProvider(id);setName(nextName);setKey('');setSettings(nextSettings);setEndpoint(nextEndpoint);baseline.current=JSON.stringify({name:nextName,key:'',settings:nextSettings,endpoint:nextEndpoint});setAdvanced(false);stack.current=['picker'];if(id==='endpoint'){setStep('endpoint');return;}if(id==='amazon-bedrock'||id==='google-vertex'){setStep('cloud-methods');return;}if(info?.authModes.length===2){setStep('methods');return;}if(info?.defaultAuthMode==='oauth'){setStep('auth');return;}setStep(serviceProviders.includes(id)?'service':'key');};
 const chooseRoute=(next:Step)=>{stack.current.push(step);setAdvanced(false);setStep(next);};
 // Start once the selected provider has rendered; never synthesize browser/device choices.
 useEffect(()=>{if(step==='auth'&&!job&&!busy&&!error&&!autoStarted.current){autoStarted.current=true;void beginOAuth();}if(step!=='auth')autoStarted.current=false;},[step,provider]);
 const submitInput=async(value:string)=>{if(!job||busy)return;setBusy(true);setError('');try{const next=await api.submitOAuthConnectionInput(job.id,value);if(alive.current){setJob(next);setCode('');}}catch(e){if(alive.current)showError(e);}finally{if(alive.current)setBusy(false);}};
 const save=async()=>{
  if(busy)return;setError('');try{
   let payload:Partial<api.ModelCredentialProfileInput>|undefined,connection:api.ProviderConnection|undefined;
   if(step==='endpoint'){
    const definition=serializeEndpoint(endpoint,existing?.models[modelIndex]);validateHeaderDrafts(endpoint.headers);
    const models=existing?[...existing.models]:[];models[modelIndex]=definition;
    const patch:Record<string,string|null>=Object.create(null);for(const stored of existing?.headerNames??[])if(!endpoint.headers.some(h=>h.name.toLowerCase()===stored.toLowerCase()))patch[stored]=null;for(const h of endpoint.headers)if(h.value||!h.stored)patch[h.name.trim()]=h.value;
    let label=definition.name||definition.id;if(!existing){const original=label;let suffix=2;while(profileNames.some(n=>n.toLocaleLowerCase()===label.toLocaleLowerCase()))label=`${original} ${suffix++}`;}
    payload={name:existing&&(existing.models.length>1||modelIndex>=existing.models.length)?existing.name:label,profileKind:'custom_endpoint',providerSlug:existing?.providerSlug??slug.current,protocol:endpoint.protocol,baseUrl:endpoint.url.trim(),authType:endpoint.key?'api_key':existing?.authType??'none',requestProfile:existing?.requestProfile??'standard',enabled:existing?.enabled??true,isDefault:existing?.isDefault??false,models,headersPatch:patch,...(endpoint.key?{apiKey:endpoint.key}:{})};
   }else if(step==='edit-name'){if(!name.trim())throw new FormError('maAddName','请填写接入名称。');payload={name:name.trim()};}
   else {if(!name.trim())throw new FormError('maAddName','请填写接入名称。');if(['key','service','aws-token','vertex-key'].includes(step)&&!key.trim()&&!existing?.hasSecret)throw new FormError('maAddKey','请输入密钥。');connection={route:step as api.ConnectionRoute,settings:step==='key'||step==='aws-token'||step==='aws-chain'||step==='vertex-key'?{}:settings};}
   setBusy(true);
   const result=connection?await api.connectProvider({providerSlug:provider,profileId:existing?.id,name:name.trim(),...(key?{apiKey:key}:{}),connection}):existing?await api.updateModelCredentialProfile(existing.id,payload!):await api.createModelCredentialProfile(payload as api.ModelCredentialProfileInput);
   if(alive.current){setKey('');onSaved(result);}
  }catch(e){if(alive.current)showError(e);}finally{if(alive.current)setBusy(false);}
 };
 const routes: Array<[Step,string]>=step==='methods'?[['key','使用 API Key'],['auth','使用账号登录']]:provider==='amazon-bedrock'?[['aws-token','使用 Bearer Token'],['aws-profile','使用 AWS profile'],['aws-chain','使用已有 AWS 凭证']]:[['vertex-key','使用 Google Cloud API Key'],['vertex-adc','使用应用默认凭证（ADC）'],['vertex-file','使用服务账号凭证文件']];
 return createPortal(<dialog ref={dialog} className="gr-small-dialog ma-add-dialog" data-step={step==='auth'?(job?.deviceCode?'device':'browser'):step} aria-labelledby="maAddTitle" onCancel={event=>{event.preventDefault();guard?setGuard(null):void leave('close');}}>
  <IconButton className="gr-dialog-close" icon="close" label={existing?reconnect?'关闭重新连接':'关闭编辑接入':'关闭添加模型'} disabled={busy} onClick={()=>void leave('close')}/>
  <div className="ma-add-body"><header className="ma-add-header">{step!=='picker'&&!existing&&<IconButton icon="chevron-left" label="返回上一步" disabled={busy} onClick={()=>void leave('back')}/>}<h1 id="maAddTitle" tabIndex={-1}>{title}</h1></header>
   <div id="maAddPicker" hidden={step!=='picker'} inert={!!guard}><label className="gr-search ma-provider-search"><Icon name="search"/><input id="maProviderSearch" type="search" aria-label="搜索供应商" placeholder="搜索供应商" value={search} onChange={e=>setSearch(e.target.value)} autoFocus/></label><div className="gr-settings-card ma-list" id="maAddFixed"><button className="gr-setting-row ma-row" onClick={()=>chooseProvider('endpoint')}><ProviderIcon slug="endpoint"/><span>自定义端点</span><Icon name="chevron-right"/></button></div><div className="ma-provider-scroll" ref={picker}>{providerLoading?<p className="ma-note">正在读取供应商…</p>:providerError?<div className="ma-error" role="alert">{providerError}<button className="gr-button" onClick={()=>setProviderRetry(v=>v+1)}>重试</button></div>:<div className="gr-settings-card ma-list">{providers.filter(p=>`${p.displayName} ${p.providerSlug}`.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase())).map(p=><button className="gr-setting-row ma-row" key={p.providerSlug} onClick={()=>chooseProvider(p.providerSlug)}><ProviderIcon slug={p.logoKey??p.providerSlug}/><span>{p.displayName}</span><Icon name="chevron-right"/></button>)}{!providers.some(p=>`${p.displayName} ${p.providerSlug}`.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase()))&&<p className="ma-provider-empty ma-note">没有匹配的供应商。</p>}</div>}</div></div>
   <div id="maAddFlow" ref={flow} hidden={step==='picker'} inert={!!guard} onInput={event=>{setError('');(event.target as HTMLElement).removeAttribute('aria-invalid');}}>
    {(step==='methods'||step==='cloud-methods')?<div className="gr-settings-card ma-list">{routes.map(([route,label])=><button className="gr-setting-row ma-row" key={route} onClick={()=>chooseRoute(route)}><span>{label}</span><Icon name="chevron-right"/></button>)}</div>:step==='auth'?<AuthFields job={job} name={name} setName={setName} code={code} setCode={setCode} busy={busy} error={error} onStart={()=>void beginOAuth()} onSubmit={value=>void submitInput(value)} onRetryRead={()=>setReadRetry(v=>v+1)} onNotice={setNotice} onCancel={async()=>{if(!job)return;generation.current++;setBusy(true);try{setJob(await api.cancelOAuthConnection(job.id));setCode('');}catch(e){showError(e);}finally{if(alive.current)setBusy(false);}}}/>:step!=='picker'?<form id={step==='endpoint'?'maEndpointForm':'maAddKeyForm'} noValidate aria-busy={busy} onSubmit={e=>{e.preventDefault();void save();}}>
     {step==='endpoint'?<EndpointFields draft={endpoint} setDraft={setEndpoint} busy={busy} storedKey={!!existing?.hasSecret} advanced={advanced} setAdvanced={setAdvanced}/>:<ConnectionFields provider={provider} route={step as api.ConnectionRoute|'edit-name'} name={name} setName={setName} apiKey={key} setKey={setKey} settings={settings} setSettings={setSettings} busy={busy} storedKey={!!existing?.hasSecret} advanced={advanced} setAdvanced={setAdvanced} onNotice={setNotice}/>}
     <p className="ma-note">{step==='edit-name'?'只修改名称，不重新授权。':'配置保存在当前 Bossmode 服务；保存不代表已验证模型连通。'}{step==='endpoint'?' 密钥和请求头值不会回显。':''}</p>{error&&<p id="maAddError" className="ma-error" role="alert" tabIndex={-1}>{error}</p>}
    </form>:null}{notice&&<p className="ma-note" role="status">{notice}</p>}
   </div>
   {!guard&&step!=='picker'&&step!=='methods'&&step!=='cloud-methods'&&step!=='auth'&&<div className="ma-add-actions ma-add-fixed"><button type="submit" form={step==='endpoint'?'maEndpointForm':'maAddKeyForm'} className="gr-button gr-primary" disabled={busy}>{busy?'正在保存…':error?'重试':'保存'}</button></div>}
   {guard&&<section id="maAddGuard" className="gr-settings-card ma-guard" aria-label={activeAuth?'取消授权？':'放弃修改？'}><p>{activeAuth?'离开会取消本次授权；已配置的接入不会删除。':'当前修改还没有保存，要放弃吗？'}</p>{error&&<p className="ma-error" role="alert">{error}</p>}<div className="ma-actions"><button id="maContinueEdit" className="gr-button" disabled={busy} onClick={()=>setGuard(null)}>继续编辑</button><button className="gr-button" disabled={busy} onClick={()=>void leave(guard,true)}>{activeAuth?'取消授权并离开':'放弃修改'}</button></div></section>}
  </div>
 </dialog>,document.body);
}
