import {WorkspaceAssets} from './WorkspaceAssets';
import {Activity} from './Activity';
import {activityView,panelMember,setPanelMember} from './pane-state';
import { MemberConfigFields } from "./MemberConfigFields";
import { AvatarPicker } from "./AvatarPicker";
import { useEffect, useLayoutEffect, useRef, useState } from 'react';
import { getMemberDetail, getMemberProfile, getRoom, getMembers, updateRoomSettings, inviteRoomMember, removeRoomMember, type MemberDetail, type Room, type RoomContact, type MemberProfileDoc } from '../api/client';
import { Avatar, GroupAvatar, Icon, IconButton, Modal, Menu, MenuItem, copyText, errorText } from './ui';
import type { ViewFile } from './Files';
interface Props {kind:'profile'|'activity'|'assets';scope:string;memberId?:string;roomId?:string;memberName?:string;username?:string;onClose:()=>void;onChanged:()=>void;onOpenFile:(file:ViewFile)=>void;onChooseModel:(memberId:string)=>void;revision?:number;onDirtyChange?:(dirty:boolean)=>void;onOpenMember?:(id:string)=>void;onRequestDelete?:()=>void}
export function GrokPane(props:Props) {
  const {kind,scope,memberId,roomId,onClose,onChanged,onOpenFile,onChooseModel,revision,onDirtyChange}=props;
  const [room,setRoom]=useState<Room|null>(null),[contacts,setContacts]=useState<RoomContact[]>([]),[member,setMember]=useState(memberId??panelMember(scope,kind)),[error,setError]=useState(''),[wide,setWide]=useState(false),[dirty,setDirty]=useState(false),[discard,setDiscard]=useState(false),[activityFind,setActivityFind]=useState(()=>activityView(memberId??panelMember(scope,kind),scope).find),[memberMenu,setMemberMenu]=useState<{x:number;y:number;width:number}|null>(null);
  const ref=useRef<HTMLElement>(null),resizeAnchor=useRef<{node:HTMLElement;list:HTMLElement;offset:number}|null>(null);
  const toggleWide=()=>{const list=ref.current?.querySelector<HTMLElement>('.gw-list,.ax-list');if(list){const top=list.getBoundingClientRect().top,node=[...list.querySelectorAll<HTMLElement>('.gw-record,.ax-file-row')].find(el=>el.getBoundingClientRect().bottom>top);if(node)resizeAnchor.current={node,list,offset:node.getBoundingClientRect().top-top};}setWide(value=>!value);};
  useEffect(()=>{let active=true;if(roomId)Promise.all([getRoom(roomId),getMembers()]).then(([r,c])=>{if(active){setRoom(r);setContacts(c);setMember(current=>{if(r.memberIds.includes(current))return current;setPanelMember(scope,kind,'');return '';});}}).catch(e=>{if(active)setError(errorText(e));});return()=>{active=false;};},[roomId,revision]);
  useEffect(()=>{const prev=document.activeElement as HTMLElement|null;ref.current?.querySelector<HTMLElement>('button')?.focus({preventScroll:true});return()=>{if(prev?.isConnected)prev.focus({preventScroll:true});};},[]);
  useLayoutEffect(()=>{const root=document.querySelector('.gr-app'),chat=document.querySelector<HTMLElement>('.gr-transcript'),chatTop=wide?chat?.scrollTop:undefined;root?.toggleAttribute(kind==='activity'?'data-work-wide':'data-assets-wide',wide);const anchor=resizeAnchor.current;if(anchor?.node.isConnected)anchor.list.scrollTop+=anchor.node.getBoundingClientRect().top-anchor.list.getBoundingClientRect().top-anchor.offset;resizeAnchor.current=null;return()=>{root?.removeAttribute('data-work-wide');root?.removeAttribute('data-assets-wide');if(chat?.isConnected&&chatTop!==undefined)chat.scrollTop=chatTop;};},[wide,kind]);
  const close=()=>dirty?setDiscard(true):onClose();
  const setDirtyState=(value:boolean)=>{setDirty(value);onDirtyChange?.(value);};
  useEffect(()=>()=>onDirtyChange?.(false),[]);
  const panelTitle=kind==='profile'?(roomId?'房间资料':'资料'):kind==='activity'?'活动':'资产';
  return <aside ref={ref} className={`gr-pane ${kind==='activity'||kind==='assets'?'gw-pane':''} ${kind==='assets'?'ax-pane':''}`} data-wide={wide?'':undefined} aria-label={panelTitle} onKeyDown={e=>{if(e.key==='Escape'&&!document.querySelector('dialog[open]')){e.preventDefault();e.stopPropagation();if(memberMenu)setMemberMenu(null);else if(kind==='activity'&&activityFind&&member)setActivityFind(false);else close();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='f'&&kind==='activity'&&member){e.preventDefault();e.stopPropagation();setMemberMenu(null);setActivityFind(true);}if(e.key==='Tab'&&innerWidth<=620&&!document.querySelector('dialog[open]')){const items=[...e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,textarea,[tabindex="0"]')].filter(el=>el.getClientRects().length);if(e.shiftKey&&document.activeElement===items[0]){e.preventDefault();items.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===items.at(-1)){e.preventDefault();items[0]?.focus();}}}}>
    <header className={kind==='profile'?'gr-pane-header':kind==='assets'?'gw-header ax-header':'gw-header'}>{kind==='profile'?<strong>{panelTitle}</strong>:<h1>{panelTitle}</h1>}{kind!=='profile'&&room&&<button className="gr-select gw-member" aria-label={`选择${panelTitle}成员`} aria-haspopup="menu" aria-expanded={!!memberMenu} onClick={e=>{const r=e.currentTarget.getBoundingClientRect();setMemberMenu({x:r.left,y:r.bottom+4,width:Math.max(220,r.width)});}}><span>{contacts.find(c=>c.id===member)?.name??'选择成员'}</span><Icon name="chevron-down"/></button>}{kind!=='profile'&&!roomId&&<span className="gw-member-name">{props.memberName??memberId}</span>}<div className={kind==='profile'?undefined:'gw-actions'}>{kind==='activity'&&<IconButton id="gwFindControl" icon="search" label="查找工作记录" disabled={!member} onClick={()=>setActivityFind(v=>!v)}/>} {kind!=='profile'&&<IconButton data-action={kind==='assets'?'ax-wide':'gw-wide'} icon={wide?'arrows-contract':'arrows-expand'} label={wide?`收起${panelTitle}`:`扩大${panelTitle}`} onClick={toggleWide}/>}<IconButton icon="chevrons-right" label={`关闭${panelTitle}`} onClick={close}/></div></header>
    {error&&<p className="gr-error">{error}</p>}{kind==='profile'?(memberId?<Profile id={memberId} revision={revision} onChanged={onChanged} onOpenFile={onOpenFile} onChooseModel={onChooseModel} onRequestDelete={props.onRequestDelete}/>:room?<RoomProfile room={room} username={props.username??'user'} contacts={contacts} onChanged={()=>{void getRoom(room.id).then(setRoom).catch(e=>setError(errorText(e)));onChanged();}} onDirty={setDirtyState} onOpenMember={props.onOpenMember} onRequestDelete={props.onRequestDelete}/>:<p className="gr-unloaded">正在加载…</p>):!member?<p className="gr-unloaded">选择一位成员，查看{panelTitle==='活动'?'工作记录':'工作区文件'}。</p>:kind==='activity'?<Activity key={member} id={member} scope={scope} find={activityFind} onCloseFind={()=>setActivityFind(false)}/>:<WorkspaceAssets key={member} id={member} onOpenFile={onOpenFile}/>}
    {memberMenu&&room&&<Menu {...memberMenu} label={`选择${panelTitle}成员`} onClose={()=>setMemberMenu(null)}>{room.memberIds.map(id=><MenuItem key={id} role="menuitemradio" aria-checked={member===id} meta={member===id?<Icon name="check"/>:undefined} onClick={()=>{setMember(id);setPanelMember(scope,kind,id);setActivityFind(activityView(id,scope).find);setMemberMenu(null);}}>{contacts.find(c=>c.id===id)?.name??id}</MenuItem>)}</Menu>}
    {discard&&<Modal title="放弃修改？" onClose={()=>setDiscard(false)}><p>房间资料的修改尚未保存。</p><div className="gr-dialog-actions"><button className="gr-button" onClick={()=>setDiscard(false)}>继续编辑</button><button className="gr-button gr-primary" onClick={()=>{setDirtyState(false);onClose();}}>放弃修改</button></div></Modal>}
  </aside>;
}
function Field({label,value}:{label:string;value?:string}) {return <div className="gr-field"><span className="gp-field-label">{label}</span><div className={`gp-field-value ${value?'':'gp-missing'}`} role="textbox" aria-label={label} aria-readonly="true" tabIndex={0}>{value||'未提供'}</div></div>;}
function Profile({id,revision,onOpenFile,onChooseModel,onChanged,onRequestDelete}:{onRequestDelete?:()=>void;id:string;revision?:number;onChanged:()=>void;onOpenFile:(f:ViewFile)=>void;onChooseModel:(id:string)=>void}) {
  const [detail,setDetail]=useState<MemberDetail|null>(null),[profile,setProfile]=useState<MemberProfileDoc|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[avatarOpen,setAvatarOpen]=useState(false),[retry,setRetry]=useState(0);
  useEffect(()=>{let live=true;Promise.all([getMemberDetail(id),getMemberProfile(id)]).then(([d,p])=>{if(live){setDetail(d);setProfile(p);setError('');}}).catch(e=>{if(live)setError(errorText(e));});return()=>{live=false;};},[id,revision,retry]);
  if(error)return <p className="gr-error" role="alert">{error} <button className="gr-button" onClick={()=>{setError('');setRetry(v=>v+1);}}>重试</button></p>;if(!detail)return <p className="gr-unloaded">正在加载资料…</p>;
  return <div className="gr-pane-body"><section className="gp-profile" aria-label="成员资料"><div className="gr-bot-hero"><button aria-label={`更改 ${detail.name} 的头像`} onClick={()=>setAvatarOpen(true)}><Avatar id={id} name={detail.name} size={68} animated/></button></div><Field label="名称" value={detail.name}/><Field label="身份" value={detail.title}/><div className="gr-field gp-persona"><div className="gp-field-heading"><span className="gp-field-label">Persona</span>{profile?.body&&<><IconButton icon="copy" label="复制 Persona 原文" onClick={()=>void copyText(profile.body).then(ok=>setNotice(ok?'已复制':'未能复制，请手动复制'))}/><IconButton icon="arrows-expand" label="查看 Persona 全文" onClick={()=>onOpenFile({name:'persona.md',content:profile.body,mimeType:'text/markdown'})}/></>}</div><div className={`gp-field-value gp-persona-text ${profile?.body?'':'gp-missing'}`} role="textbox" aria-readonly="true" aria-multiline="true" aria-label="Persona" tabIndex={0}>{profile?.body||'暂无 Persona'}</div></div><MemberConfigFields member={detail} onSaved={member=>{setDetail(member);onChanged();}}/><dl className="gp-created">{[['创建日期',detail.createdAt],['更新日期',detail.updatedAt]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value?new Date(Number(value)).toLocaleDateString('zh-CN'):'未提供'}</dd></div>)}</dl>{notice&&<p role="status" className="gr-small">{notice}</p>}</section><div className="mc-profile-danger"><button onClick={onRequestDelete}>删除成员</button></div>{avatarOpen&&<AvatarPicker member={detail} onClose={()=>setAvatarOpen(false)} onSaved={member=>{setDetail(member);onChanged();}}/>}</div>;
}
function RoomProfile({room,username,contacts,onChanged,onDirty,onOpenMember,onRequestDelete}:{username:string;onRequestDelete?:()=>void;onOpenMember?:(id:string)=>void;room:Room;contacts:RoomContact[];onChanged:()=>void;onDirty:(v:boolean)=>void}) {
  const [editing,setEditing]=useState(false),[name,setName]=useState(room.name),[description,setDescription]=useState(room.description??''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[add,setAdd]=useState<{x:number;y:number}|null>(null),[remove,setRemove]=useState<RoomContact|null>(null),[discard,setDiscard]=useState(false);
  const dirty=editing&&(name!==room.name||description!==(room.description??''));useEffect(()=>{onDirty(dirty);},[dirty]);
  const cancel=()=>{setEditing(false);setName(room.name);setDescription(room.description??'');onDirty(false);};
  return <div className="gr-pane-body"><section className="ru-profile"><div className="gr-bot-hero"><GroupAvatar members={room.memberIds} size={64} username={username}/></div>{editing?<form onSubmit={async e=>{e.preventDefault();if(!name.trim()||description.trim().length>2000){setError('请填写名称，描述最多 2000 字符。');return;}setBusy(true);try{await updateRoomSettings(room.id,{name:name.trim(),description:description.trim()||null});setEditing(false);onDirty(false);onChanged();}catch(e){setError(errorText(e));}finally{setBusy(false);}}}><div className="gr-field"><label htmlFor="roomName">名称</label><input id="roomName" value={name} onChange={e=>setName(e.target.value)} disabled={busy} autoFocus/></div><div className="gr-field"><label htmlFor="roomDescription">描述</label><textarea id="roomDescription" value={description} onChange={e=>setDescription(e.target.value)} disabled={busy}/><span className="ru-count">{description.trim().length} / 2000</span></div><div className="ru-actions"><button type="button" className="gr-button" disabled={busy} onClick={()=>dirty?setDiscard(true):cancel()}>取消</button><button className="gr-button gr-primary" disabled={busy}>{busy?'正在保存…':'保存'}</button></div></form>:<><div className="gr-field"><div className="gp-field-heading"><span className="gp-field-label">名称</span><button className="ru-edit" aria-label="编辑房间资料" onClick={()=>{setName(room.name);setDescription(room.description??'');setEditing(true);setError('');}}>编辑</button></div><div className="gp-field-value">{room.name}</div></div><Field label="描述" value={room.description||'暂无描述'}/></>}</section>{error&&<p className="gr-error" role="alert">{error}</p>}<section className="gc-members" aria-label="群成员"><div className="gr-small gc-members-heading">成员</div><ul>{room.memberIds.map(id=>{const c=contacts.find(c=>c.id===id)??{id,name:id};return <li key={id}><button className="gc-member-open" onClick={()=>onOpenMember?.(id)}><Avatar id={id} size={28}/><span>{c.name}</span></button><button className="gc-member-remove" aria-label={`移除 ${c.name}`} onClick={()=>{setError('');setRemove(c);}}>移除</button></li>;})}<li><button className="gc-member-add" aria-haspopup="menu" aria-expanded={!!add} onClick={e=>{setError('');const r=e.currentTarget.getBoundingClientRect();setAdd({x:r.left,y:r.bottom+4});}}><Icon name="add"/>添加成员</button></li></ul><button className="gc-delete-group" onClick={onRequestDelete}>删除群聊</button></section>
    {add&&<Menu {...add} label="添加群成员" onClose={()=>setAdd(null)}>{!contacts.some(c=>!room.memberIds.includes(c.id))&&<p className="gc-no-candidates">没有其他可添加的成员</p>}{error&&<p className="gr-error" role="alert">{error}</p>}{busy&&<p role="status" className="gr-small">正在添加成员…</p>}{contacts.filter(c=>!room.memberIds.includes(c.id)).map(c=><MenuItem key={c.id} disabled={busy} onClick={async()=>{setBusy(true);try{await inviteRoomMember(room.id,c.id);onChanged();setAdd(null);}catch(e){setError(errorText(e));}finally{setBusy(false);}}}>{c.name}</MenuItem>)}</Menu>}
    {remove&&<Modal title={`移出 ${remove.name}？`} onClose={()=>{if(!busy)setRemove(null);}}><p>只从当前群聊移出，不删除成员和已发送的消息。</p>{error&&<p className="gr-error" role="alert">{error}</p>}<div className="gr-dialog-actions"><button className="gr-button" disabled={busy} onClick={()=>setRemove(null)}>取消</button><button className="gr-button gr-primary" disabled={busy} onClick={async()=>{setBusy(true);try{await removeRoomMember(room.id,remove.id);onChanged();setRemove(null);}catch(e){setError(errorText(e));}finally{setBusy(false);}}}>{busy?'正在移出…':'移出群聊'}</button></div></Modal>}
    {discard&&<Modal title="放弃修改？" onClose={()=>setDiscard(false)}><p>修改尚未保存。</p><div className="gr-dialog-actions"><button className="gr-button" onClick={()=>setDiscard(false)}>继续编辑</button><button className="gr-button gr-primary" onClick={()=>{setDiscard(false);cancel();}}>放弃修改</button></div></Modal>}
  </div>;
}
