import {WorkspaceAssets} from './WorkspaceAssets';
import { mergeActivityEvents, activityRecords, activityLabel } from "./activity-records";
import { MemberConfigFields } from "./MemberConfigFields";
import { AvatarPicker } from "./AvatarPicker";
import { useCallback, useEffect, useRef, useState } from 'react';
import { getMemberDetail, getMemberProfile, getRoom, getMembers, updateRoomSettings, inviteRoomMember, removeRoomMember, getMemberScopedActivityEvents, getConversationSession, memberAction, abortMember, type MemberDetail, type Room, type RoomContact, type MemberProfileDoc, type ConversationSessionInfo } from '../api/client';
import { formatToolArgsFull, summarizeAgentEvent, isActivityStreamEvent, type AgentEvent } from '../components/agent-event-utils';
import { Avatar, GroupAvatar, Icon, IconButton, Modal, Menu, MenuItem, copyText, errorText } from './ui';
import type { ViewFile } from './Files';
interface Props {kind:'profile'|'activity'|'assets';scope:string;memberId?:string;roomId?:string;onClose:()=>void;onChanged:()=>void;onOpenFile:(file:ViewFile)=>void;onChooseModel:(memberId:string)=>void;revision?:number;onDirtyChange?:(dirty:boolean)=>void;onOpenMember?:(id:string)=>void;onRequestDelete?:()=>void}
export function GrokPane(props:Props) {
  const {kind,scope,memberId,roomId,onClose,onChanged,onOpenFile,onChooseModel,revision,onDirtyChange}=props;
  const [room,setRoom]=useState<Room|null>(null),[contacts,setContacts]=useState<RoomContact[]>([]),[member,setMember]=useState(memberId??''),[error,setError]=useState(''),[wide,setWide]=useState(false),[dirty,setDirty]=useState(false),[discard,setDiscard]=useState(false),[activityFind,setActivityFind]=useState(false);
  const ref=useRef<HTMLElement>(null);
  useEffect(()=>{let active=true;if(roomId)Promise.all([getRoom(roomId),getMembers()]).then(([r,c])=>{if(active){setRoom(r);setContacts(c);}}).catch(e=>{if(active)setError(errorText(e));});return()=>{active=false;};},[roomId,revision]);
  useEffect(()=>{const prev=document.activeElement as HTMLElement|null;ref.current?.querySelector<HTMLElement>('button')?.focus({preventScroll:true});return()=>{if(prev?.isConnected)prev.focus({preventScroll:true});};},[]);
  useEffect(()=>{const root=document.querySelector('.gr-app');root?.toggleAttribute(kind==='activity'?'data-work-wide':'data-assets-wide',wide);return()=>{root?.removeAttribute('data-work-wide');root?.removeAttribute('data-assets-wide');};},[wide,kind]);
  const close=()=>dirty?setDiscard(true):onClose();
  const setDirtyState=(value:boolean)=>{setDirty(value);onDirtyChange?.(value);};
  useEffect(()=>()=>onDirtyChange?.(false),[]);
  const panelTitle=kind==='profile'?(roomId?'房间资料':'资料'):kind==='activity'?'活动':'资产';
  return <aside ref={ref} className={`gr-pane ${kind==='activity'||kind==='assets'?'gw-pane':''}`} data-wide={wide?'':undefined} aria-label={panelTitle} onKeyDown={e=>{if(e.key==='Escape'&&!document.querySelector('dialog[open]')){e.preventDefault();e.stopPropagation();close();}if(e.key==='Tab'&&innerWidth<=620&&!document.querySelector('dialog[open]')){const items=[...e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,textarea,[tabindex="0"]')].filter(el=>el.getClientRects().length);if(e.shiftKey&&document.activeElement===items[0]){e.preventDefault();items.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===items.at(-1)){e.preventDefault();items[0]?.focus();}}}}>
    <header className={kind==='profile'?'gr-pane-header':'gw-header'}>{kind==='profile'?<strong>{panelTitle}</strong>:<h1>{panelTitle}</h1>}{kind!=='profile'&&room&&<select className="gr-select gw-member" aria-label={`选择${panelTitle}成员`} value={member} onChange={e=>setMember(e.target.value)}><option value="">选择成员</option>{room.memberIds.map(id=><option key={id} value={id}>{contacts.find(c=>c.id===id)?.name??id}</option>)}</select>}{kind!=='profile'&&!roomId&&<span className="gw-member-name"/>}<div className={kind==='profile'?undefined:'gw-actions'}>{kind==='activity'&&<IconButton icon="search" label="查找工作记录" disabled={!member} onClick={()=>setActivityFind(v=>!v)}/>} {kind!=='profile'&&<IconButton icon={wide?'arrows-contract':'arrows-expand'} label={wide?`收起${panelTitle}`:`扩大${panelTitle}`} onClick={()=>setWide(v=>!v)}/>}<IconButton icon="chevrons-right" label={`关闭${panelTitle}`} onClick={close}/></div></header>
    {error&&<p className="gr-error">{error}</p>}{kind==='profile'?(memberId?<Profile id={memberId} revision={revision} onChanged={onChanged} onOpenFile={onOpenFile} onChooseModel={onChooseModel} onRequestDelete={props.onRequestDelete}/>:room?<RoomProfile room={room} contacts={contacts} onChanged={()=>{void getRoom(room.id).then(setRoom);onChanged();}} onDirty={setDirtyState} onOpenMember={props.onOpenMember} onRequestDelete={props.onRequestDelete}/>:<p className="gr-unloaded">正在加载…</p>):!member?<p className="gr-unloaded">选择一位成员，查看{panelTitle==='活动'?'工作记录':'工作区文件'}。</p>:kind==='activity'?<Activity key={member} id={member} scope={scope} find={activityFind} onCloseFind={()=>setActivityFind(false)}/>:<WorkspaceAssets key={member} id={member} onOpenFile={onOpenFile}/>}
    {discard&&<Modal title="放弃修改？" onClose={()=>setDiscard(false)}><p>房间资料的修改尚未保存。</p><div className="gr-dialog-actions"><button className="gr-button" onClick={()=>setDiscard(false)}>继续编辑</button><button className="gr-button gr-primary" onClick={()=>{setDirtyState(false);onClose();}}>放弃修改</button></div></Modal>}
  </aside>;
}
function Field({label,value}:{label:string;value?:string}) {return <div className="gr-field"><span className="gp-field-label">{label}</span><div className={`gp-field-value ${value?'':'gp-missing'}`} role="textbox" aria-label={label} aria-readonly="true" tabIndex={0}>{value||'未提供'}</div></div>;}
function Profile({id,revision,onOpenFile,onChooseModel,onChanged,onRequestDelete}:{onRequestDelete?:()=>void;id:string;revision?:number;onChanged:()=>void;onOpenFile:(f:ViewFile)=>void;onChooseModel:(id:string)=>void}) {
  const [detail,setDetail]=useState<MemberDetail|null>(null),[profile,setProfile]=useState<MemberProfileDoc|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[avatarOpen,setAvatarOpen]=useState(false);
  useEffect(()=>{let live=true;Promise.all([getMemberDetail(id),getMemberProfile(id)]).then(([d,p])=>{if(live){setDetail(d);setProfile(p);setError('');}}).catch(e=>{if(live)setError(errorText(e));});return()=>{live=false;};},[id,revision]);
  if(error)return <p className="gr-error">{error}</p>;if(!detail)return <p className="gr-unloaded">正在加载资料…</p>;
  return <div className="gr-pane-body"><section className="gp-profile" aria-label="成员资料"><div className="gr-bot-hero"><button aria-label={`更改 ${detail.name} 的头像`} onClick={()=>setAvatarOpen(true)}><Avatar id={id} name={detail.name} size={68}/></button></div><Field label="名称" value={detail.name}/><Field label="身份" value={detail.title}/><div className="gr-field gp-persona"><div className="gp-field-heading"><span className="gp-field-label">Persona</span>{profile?.body&&<><IconButton icon="copy" label="复制 Persona 原文" onClick={()=>void copyText(profile.body).then(ok=>setNotice(ok?'已复制':'未能复制，请手动复制'))}/><IconButton icon="arrows-expand" label="查看 Persona 全文" onClick={()=>onOpenFile({name:'persona.md',content:profile.body,mimeType:'text/markdown'})}/></>}</div><div className={`gp-field-value gp-persona-text ${profile?.body?'':'gp-missing'}`} role="textbox" aria-readonly="true" aria-multiline="true" aria-label="Persona" tabIndex={0}>{profile?.body||'暂无 Persona'}</div></div><MemberConfigFields member={detail} onSaved={member=>{setDetail(member);onChanged();}}/><dl className="gp-created">{[['创建日期',detail.createdAt],['更新日期',detail.updatedAt]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value?new Date(Number(value)).toLocaleDateString('zh-CN'):'未提供'}</dd></div>)}</dl>{notice&&<p role="status" className="gr-small">{notice}</p>}</section><div className="mc-profile-danger"><button onClick={onRequestDelete}>删除成员</button></div>{avatarOpen&&<AvatarPicker member={detail} onClose={()=>setAvatarOpen(false)} onSaved={member=>{setDetail(member);onChanged();}}/>}</div>;
}
function RoomProfile({room,contacts,onChanged,onDirty,onOpenMember,onRequestDelete}:{onRequestDelete?:()=>void;onOpenMember?:(id:string)=>void;room:Room;contacts:RoomContact[];onChanged:()=>void;onDirty:(v:boolean)=>void}) {
  const [editing,setEditing]=useState(false),[name,setName]=useState(room.name),[description,setDescription]=useState(room.description??''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[add,setAdd]=useState(false),[remove,setRemove]=useState<RoomContact|null>(null),[discard,setDiscard]=useState(false);
  const dirty=editing&&(name!==room.name||description!==(room.description??''));useEffect(()=>{onDirty(dirty);},[dirty]);
  const cancel=()=>{setEditing(false);setName(room.name);setDescription(room.description??'');onDirty(false);};
  return <div className="gr-pane-body"><section className="ru-profile"><div className="gr-bot-hero"><GroupAvatar members={room.memberIds} size={64}/></div>{editing?<form onSubmit={async e=>{e.preventDefault();if(!name.trim()||description.trim().length>2000){setError('请填写名称，描述最多 2000 字符。');return;}setBusy(true);try{await updateRoomSettings(room.id,{name:name.trim(),description:description.trim()||null});setEditing(false);onDirty(false);onChanged();}catch(e){setError(errorText(e));}finally{setBusy(false);}}}><div className="gr-field"><label htmlFor="roomName">名称</label><input id="roomName" value={name} onChange={e=>setName(e.target.value)} disabled={busy} autoFocus/></div><div className="gr-field"><label htmlFor="roomDescription">描述</label><textarea id="roomDescription" value={description} onChange={e=>setDescription(e.target.value)} disabled={busy}/><span className="ru-count">{description.trim().length} / 2000</span></div><div className="ru-actions"><button type="button" className="gr-button" disabled={busy} onClick={()=>dirty?setDiscard(true):cancel()}>取消</button><button className="gr-button gr-primary" disabled={busy}>{busy?'正在保存…':'保存'}</button></div></form>:<><div className="gr-field"><div className="gp-field-heading"><span className="gp-field-label">名称</span><button className="ru-edit" aria-label="编辑房间资料" onClick={()=>{setName(room.name);setDescription(room.description??'');setEditing(true);setError('');}}>编辑</button></div><div className="gp-field-value">{room.name}</div></div><Field label="描述" value={room.description||'暂无描述'}/></>}</section>{error&&<p className="gr-error" role="alert">{error}</p>}<section className="gc-members" aria-label="群成员"><div className="gr-small gc-members-heading">成员</div><ul>{room.memberIds.map(id=>{const c=contacts.find(c=>c.id===id)??{id,name:id};return <li key={id}><button className="gc-member-open" onClick={()=>onOpenMember?.(id)}><Avatar id={id} size={28}/><span>{c.name}</span></button><button className="gc-member-remove" aria-label={`移除 ${c.name}`} onClick={()=>setRemove(c)}>移除</button></li>;})}<li><button className="gc-member-add" onClick={()=>setAdd(true)}><Icon name="add"/>添加成员</button></li></ul><button className="gc-delete-group" onClick={onRequestDelete}>删除群聊</button></section>
    {add&&<Modal title="添加群成员" onClose={()=>setAdd(false)}>{contacts.filter(c=>!room.memberIds.includes(c.id)).map(c=><button className="gr-recipient-row" key={c.id} disabled={busy} onClick={async()=>{setBusy(true);try{await inviteRoomMember(room.id,c.id);onChanged();setAdd(false);}catch(e){setError(errorText(e));}finally{setBusy(false);}}}><Avatar id={c.id} size={24}/>{c.name}</button>)}</Modal>}
    {remove&&<Modal title={`移出 ${remove.name}？`} onClose={()=>setRemove(null)}><p>只从当前群聊移出，不删除成员和已发送的消息。</p><div className="gr-dialog-actions"><button className="gr-button" onClick={()=>setRemove(null)}>取消</button><button className="gr-button gr-primary" disabled={busy} onClick={async()=>{setBusy(true);try{await removeRoomMember(room.id,remove.id);onChanged();setRemove(null);}catch(e){setError(errorText(e));}finally{setBusy(false);}}}>移出群聊</button></div></Modal>}
    {discard&&<Modal title="放弃修改？" onClose={()=>setDiscard(false)}><p>修改尚未保存。</p><div className="gr-dialog-actions"><button className="gr-button" onClick={()=>setDiscard(false)}>继续编辑</button><button className="gr-button gr-primary" onClick={()=>{setDiscard(false);cancel();}}>放弃修改</button></div></Modal>}
  </div>;
}
const opNames={stop:'停止工作',compact:'压缩会话',restart:'重启成员',reset:'重置会话'};
function Activity({id,scope,find,onCloseFind}:{id:string;scope:string;find:boolean;onCloseFind:()=>void}) {
  const [session,setSession]=useState<ConversationSessionInfo|null>(null),[events,setEvents]=useState<AgentEvent[]>([]),[before,setBefore]=useState<number|undefined>(),[hasMore,setHasMore]=useState(false),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[menu,setMenu]=useState<{x:number;y:number}|null>(null),[confirm,setConfirm]=useState<'reset'|'restart'|null>(null);
  const load=useCallback(async()=>{try{const [s,e]=await Promise.all([getConversationSession(scope,id),getMemberScopedActivityEvents(id,scope,120)]);setSession(s);setEvents(old=>mergeActivityEvents(old,e.events as AgentEvent[]));setBefore(v=>v??e.nextBeforeSeq??undefined);setHasMore(e.hasMore);setError('');}catch(e){setError(errorText(e));}},[scope,id]);
  useEffect(()=>{void load();const t=setInterval(()=>void load(),4000);return()=>clearInterval(t);},[load]);
  const operate=async(kind:keyof typeof opNames)=>{setConfirm(null);setMenu(null);setBusy(true);setNotice('');try{const result=kind==='stop'?await abortMember(id):await memberAction(id,kind);setNotice((result as {message?:string}).message||`${opNames[kind]}请求已处理。`);await load();}catch(e){setError(errorText(e));}finally{setBusy(false);}};
  const records=activityRecords(events).filter(({event:e,end})=>!query||JSON.stringify([e,end,activityLabel(e)]).toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  return <><div className="gw-hero"><Avatar id={id} size={76} status={session?.status}/></div><section className="gw-controls"><div className="gw-control-row"><span className="gw-state" role="status">{session?session.busy.busy?'工作中':'待命':'正在同步状态…'}</span><button className="gr-button" disabled={busy||!session?.busy.busy} onClick={()=>void operate('stop')}><Icon name="stop"/>停止工作</button><IconButton icon="ellipsis" label="更多操作" disabled={busy||!session} onClick={e=>{const r=e.currentTarget.getBoundingClientRect();setMenu({x:r.left-180,y:r.bottom});}}/></div><p className="gw-impact">作用于该成员的所有聊天；停止、重启、重置会取消待处理工作。</p>{notice&&<p className="gw-outcome" role="status">{notice}</p>}{error&&<p className="gr-error" role="alert">{error} <button onClick={()=>void load()}>重试</button></p>}</section><div className="gw-scope">成员工作记录</div>{find&&<div className="gw-search"><Icon name="search"/><input type="search" aria-label="查找本页工作记录" placeholder="查找工作记录" value={query} onChange={e=>setQuery(e.target.value)} autoFocus/><IconButton icon="close" label="关闭工作记录查找" onClick={()=>{onCloseFind();setQuery('');}}/></div>}<div className="gw-list" tabIndex={0} aria-label="工作记录列表">{hasMore&&<button className="gr-load-older" onClick={async()=>{try{const e=await getMemberScopedActivityEvents(id,scope,120,before);setEvents(prev=>mergeActivityEvents(e.events as AgentEvent[],prev));setBefore(e.nextBeforeSeq??undefined);setHasMore(e.hasMore);}catch(e){setError(errorText(e));}}}>加载更早记录</button>}{!records.length&&<p className="gw-empty">{query?'没有匹配记录':'暂无工作记录'}</p>}<div className="gw-accordion">{records.map(({event:e,end},i)=>{const summary=summarizeAgentEvent(end??e),status=e.type==='tool_start'?(end?end.isError?'失败':'已完成':'未收到结果'):e.isError?'失败':'';return <details className="gw-record" key={String(e.seq??i)}><summary><span className="gw-status-icon" data-status={status==='失败'?'error':end?'done':'missing'}><Icon name={status==='失败'?'close':'check'}/></span><span className="gw-action"><span className="gw-action-label">{activityLabel(e)}</span><time>{e.ts?new Date(e.ts).toLocaleTimeString('zh-CN'):''}</time></span><span className="gw-result">{status}</span><span className="gw-chevron"><Icon name="chevron-down"/></span></summary><div className="gw-detail">{e.args!==undefined&&<RecordBlock title="参数" text={formatToolArgsFull(e.args)} onNotice={setNotice}/>}<RecordBlock title="输出" text={formatToolArgsFull(end?.result??e.result??e.text??e.thinking??summary.detail??'未记录')} onNotice={setNotice}/>{e.type==='tool_start'&&!end&&<p className="gw-detail-note">记录中没有返回结果，不能据此判断是否仍在执行。</p>}</div></details>;})}</div></div>
    {menu&&<Menu {...menu} onClose={()=>setMenu(null)}>{(['compact','restart','reset'] as const).map(kind=><MenuItem key={kind} onClick={()=>kind==='compact'?void operate(kind):(setMenu(null),setConfirm(kind))}>{opNames[kind]}</MenuItem>)}</Menu>}
    {confirm&&<Modal title={`${opNames[confirm]} ${session?.memberName??'成员'}？`} onClose={()=>setConfirm(null)}><p>{confirm==='reset'?'结束当前工作并重置上下文，下次从新会话开始。':'结束当前工作并重新加载成员，已有上下文保留。'}</p><p>这会影响该成员的所有聊天，并取消尚未处理的工作。历史消息和成员资料不删除；已执行的外部操作不会撤回，后台命令可能继续运行。</p><div className="gr-dialog-actions"><button className="gr-button" onClick={()=>setConfirm(null)}>取消</button><button className="gr-button gr-primary" onClick={()=>void operate(confirm)}>{opNames[confirm]}</button></div></Modal>}
  </>;
}
function RecordBlock({title,text,onNotice}:{title:string;text:string;onNotice:(s:string)=>void}) {return <section className="gw-block"><header><span>{title}</span><IconButton icon="copy" label={`复制${title}`} onClick={()=>void copyText(text).then(ok=>onNotice(ok?'已复制':'未能复制，请手动复制'))}/></header><pre tabIndex={0} aria-label={`${title}原文`}>{text}</pre></section>;}
