import { useEffect, useRef, useState } from 'react';
import type { RoomContact, MessageSearchHit, MessageSearchAuthor } from '../api/client';
import { searchMessages } from './api';
import {searchExcerpt} from './search-text';
import {SelectMenu} from './SelectMenu';
import { Icon, IconButton, errorText } from './ui';
function Excerpt({text,query}:{text:string;query:string}){const part=searchExcerpt(text,query);return <>{part.before}{part.match&&<mark>{part.match}</mark>}{part.after}</>;}
export function Search({scope,contacts,username,onClose,onJump,revision}:{scope:string;revision?:number;contacts:RoomContact[];username:string;onClose:()=>void;onJump:(id:string)=>Promise<void>}) {
  const [query,setQuery]=useState(''),[author,setAuthor]=useState(''),[date,setDate]=useState(''),[results,setResults]=useState<MessageSearchHit[]>([]),[total,setTotal]=useState(0),[status,setStatus]=useState('idle'),[error,setError]=useState(''),[viewing,setViewing]=useState(false),[selected,setSelected]=useState(''),[retry,setRetry]=useState(0);
  const [authors,setAuthors]=useState<MessageSearchAuthor[]>([]),[authorsLoading,setAuthorsLoading]=useState(true),[authorsError,setAuthorsError]=useState(''),[authorsRetry,setAuthorsRetry]=useState(0);
  const rosterKey=JSON.stringify(contacts.map(m=>[m.id,m.name]));
  useEffect(()=>{const controller=new AbortController();setAuthorsLoading(true);setAuthorsError('');searchMessages(scope,{query:'',author:'',date:'',offset:0,limit:1,includeAuthors:true,signal:controller.signal}).then(result=>{if(controller.signal.aborted)return;if(!Array.isArray(result.authors))throw Error('服务器未返回作者列表。');setAuthors(result.authors);setAuthor(previous=>!previous||result.authors!.some(row=>row.id===previous)?previous:'');}).catch(e=>{if(!controller.signal.aborted)setAuthorsError(errorText(e));}).finally(()=>{if(!controller.signal.aborted)setAuthorsLoading(false);});return()=>controller.abort();},[scope,rosterKey,revision,authorsRetry]);
  const authorOption=(a:MessageSearchAuthor)=>({value:a.id,label:a.kind==='user'?username:a.name,detail:a.status==='left'?'已退出':a.status==='deleted'?'已删除':a.kind==='legacy'?'旧记录':undefined});
  const authorGroups=[['当前成员',authors.filter(a=>a.status==='current')],['历史成员',authors.filter(a=>a.status==='left'||a.status==='deleted')],['其他作者',authors.filter(a=>a.status==='unknown')]] as const;
  const epoch=useRef(0),input=useRef<HTMLInputElement>(null),scroll=useRef<HTMLDivElement>(null),scrollTop=useRef(0); const active=!!(query.trim()||author||date);
  useEffect(()=>{const previous=document.activeElement as HTMLElement|null;input.current?.focus();return()=>{if(previous?.isConnected)previous.focus({preventScroll:true});};},[]);
  useEffect(()=>{const current=++epoch.current;setViewing(false);setSelected('');setResults([]);setTotal(0);setError('');if(!active){setStatus('idle');return;}setStatus('loading');const t=setTimeout(()=>{searchMessages(scope,{query:query.trim(),author,date,offset:0}).then(r=>{if(current!==epoch.current)return;setResults(r.messages);setTotal(r.total);setStatus('ready');}).catch(e=>{if(current===epoch.current){setStatus('error');setError(errorText(e));}});},250);return()=>{clearTimeout(t);epoch.current++;};},[scope,query,author,date,retry]);
  const more=async()=>{const current=epoch.current,top=scroll.current?.scrollTop??0;setError('');setStatus('more');try{const r=await searchMessages(scope,{query:query.trim(),author,date,offset:results.length});if(current!==epoch.current)return;setResults(prev=>[...prev,...r.messages]);setTotal(r.total);setStatus('ready');requestAnimationFrame(()=>{if(current===epoch.current&&scroll.current)scroll.current.scrollTop=top;});}catch(e){if(current===epoch.current){setStatus('ready');setError(errorText(e));}}};
  const jump=async(id:string)=>{const current=epoch.current;setSelected(id);scrollTop.current=scroll.current?.scrollTop??0;setStatus('locating');try{await onJump(id);if(current===epoch.current){setViewing(true);setStatus('ready');}}catch(e){if(current===epoch.current){setError(errorText(e));setStatus('ready');}}};
  return <section className={`gc-find ss-search ${viewing?'ss-viewing':''}`} aria-label="消息搜索" onKeyDown={e=>{if(e.key==='Escape'&&!e.nativeEvent.isComposing){e.preventDefault();onClose();}}}>
    <div className="gc-find-bar"><Icon name="search"/><input ref={input} type="search" placeholder="搜索当前聊天的消息" aria-label="搜索当前聊天的消息" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.nativeEvent.isComposing)return;if(e.key==='Enter'&&results.length){e.preventDefault();void jump(results[0].id);}if(e.key==='ArrowDown'){e.preventDefault();scroll.current?.querySelector<HTMLButtonElement>('button')?.focus();}}}/><IconButton icon="close" label="关闭消息搜索" onClick={onClose}/></div>
    <div className="ss-filters"><label><span>发言人</span><SelectMenu label="筛选发言人" className="ss-filter-select ss-author-select" value={author} disabled={!!authorsError||authorsLoading&&!authors.length} onChange={setAuthor} groups={[{options:[{value:'',label:authorsLoading&&!authors.length?'正在读取作者…':'所有人'}]},...authorGroups.map(([label,rows])=>({label,options:rows.map(authorOption)}))]}/></label><label><span>日期</span><SelectMenu label="筛选日期" className="ss-filter-select ss-date-select" value={date} onChange={setDate} groups={[{options:[{value:'',label:'全部日期'},{value:'today',label:'今天'},{value:'7',label:'近7天'},{value:'30',label:'近30天'}]}]}/></label>{active&&<button className="ss-reset" onClick={()=>{setQuery('');setAuthor('');setDate('');input.current?.focus();}}>重置</button>}</div>
    {authorsError&&<p className="gr-error" role="alert">作者列表未更新：{authorsError} <button onClick={()=>setAuthorsRetry(value=>value+1)}>重试作者列表</button></p>}
    <div className="ss-summary" role="status">{viewing?<button className="ss-back" onClick={()=>{setViewing(false);requestAnimationFrame(()=>{if(scroll.current){scroll.current.scrollTop=scrollTop.current;scroll.current.querySelector<HTMLButtonElement>('[aria-current="true"]')?.focus({preventScroll:true});}});}}><Icon name="chevron-left"/>返回 {total} 条搜索结果</button>:status==='ready'||status==='more'||status==='locating'?`${total} 条结果 · 当前聊天的全部记录`:''}</div>
    <div className="ss-results" ref={scroll} hidden={viewing} aria-label="消息搜索结果" tabIndex={0}>{error&&<p className="gr-error" role="alert">{error} <button onClick={()=>setRetry(v=>v+1)}>重试</button></p>}{status==='idle'?<p className="ss-empty">输入关键词，或选择发言人和日期。</p>:status==='loading'?<p className="ss-empty">正在搜索…</p>:<><ol>{results.map(m=><li key={m.id}><button className="ss-result" aria-current={selected===m.id?'true':undefined} disabled={status==='locating'} onClick={()=>void jump(m.id)}><span className="ss-result-meta"><strong>{m.sender==='user'?username:authors.find(a=>a.memberId===m.senderMemberId&&a.kind==='member')?.name??contacts.find(c=>c.id===m.senderMemberId)?.name??m.sender}</strong><time>{new Date(m.ts).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}</time></span><span className="ss-excerpt"><Excerpt text={m.content||'附件消息'} query={query}/></span>{status==='locating'&&selected===m.id&&<span className="ss-locating">正在定位…</span>}</button></li>)}</ol>{!results.length&&status!=='error'&&<p className="ss-empty">没有找到匹配的消息。</p>}{results.length>0&&results.length<total&&<button className="gr-button ss-more" disabled={status==='more'} onClick={()=>void more()}>{status==='more'?'正在加载…':'查看更多结果'}</button>}</>}</div>
  </section>;
}
