import { useEffect, useRef, useState } from 'react';
import type { RoomContact, MessageSearchHit } from '../api/client';
import { searchMessages } from './api';
import { Icon, IconButton, errorText } from './ui';
export function Search({scope,contacts,username,onClose,onJump}:{scope:string;contacts:RoomContact[];username:string;onClose:()=>void;onJump:(id:string)=>Promise<void>}) {
  const [query,setQuery]=useState(''),[author,setAuthor]=useState(''),[date,setDate]=useState(''),[results,setResults]=useState<MessageSearchHit[]>([]),[total,setTotal]=useState(0),[status,setStatus]=useState('idle'),[error,setError]=useState(''),[viewing,setViewing]=useState(false),[selected,setSelected]=useState(''),[retry,setRetry]=useState(0);
  const epoch=useRef(0),input=useRef<HTMLInputElement>(null),scroll=useRef<HTMLDivElement>(null),scrollTop=useRef(0); const active=!!(query.trim()||author||date);
  useEffect(()=>{input.current?.focus();},[]);
  useEffect(()=>{const current=++epoch.current;setViewing(false);setSelected('');setResults([]);setError('');if(!active){setStatus('idle');return;}setStatus('loading');const t=setTimeout(()=>{searchMessages(scope,{query:query.trim(),author,date,offset:0}).then(r=>{if(current!==epoch.current)return;setResults(r.messages);setTotal(r.total);setStatus('ready');}).catch(e=>{if(current===epoch.current){setStatus('error');setError(errorText(e));}});},250);return()=>{clearTimeout(t);epoch.current++;};},[scope,query,author,date,retry]);
  const more=async()=>{const current=epoch.current;setStatus('more');try{const r=await searchMessages(scope,{query:query.trim(),author,date,offset:results.length});if(current!==epoch.current)return;setResults(prev=>[...prev,...r.messages]);setTotal(r.total);setStatus('ready');}catch(e){if(current===epoch.current){setStatus('ready');setError(errorText(e));}}};
  const jump=async(id:string)=>{const current=epoch.current;setSelected(id);scrollTop.current=scroll.current?.scrollTop??0;setStatus('locating');try{await onJump(id);if(current===epoch.current){setViewing(true);setStatus('ready');}}catch(e){if(current===epoch.current){setError(errorText(e));setStatus('ready');}}};
  return <section className={`gc-find ss-search ${viewing?'ss-viewing':''}`} aria-label="消息搜索" onKeyDown={e=>{if(e.key==='Escape'&&!e.nativeEvent.isComposing){e.preventDefault();onClose();}}}>
    <div className="gc-find-bar"><Icon name="search"/><input ref={input} type="search" placeholder="搜索当前聊天的消息" aria-label="搜索当前聊天的消息" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.nativeEvent.isComposing)return;if(e.key==='Enter'&&results.length){e.preventDefault();void jump(results[0].id);}if(e.key==='ArrowDown'){e.preventDefault();scroll.current?.querySelector<HTMLButtonElement>('button')?.focus();}}}/><IconButton icon="close" label="关闭消息搜索" onClick={onClose}/></div>
    <div className="ss-filters"><label><span>发言人</span><select aria-label="筛选发言人" value={author} onChange={e=>setAuthor(e.target.value)}><option value="">所有人</option><option value="user">{username}</option>{contacts.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label><span>日期</span><select aria-label="筛选日期" value={date} onChange={e=>setDate(e.target.value)}><option value="">全部日期</option><option value="today">今天</option><option value="7">近7天</option><option value="30">近30天</option></select></label>{active&&<button className="ss-reset" onClick={()=>{setQuery('');setAuthor('');setDate('');input.current?.focus();}}>重置</button>}</div>
    <div className="ss-summary" role="status">{viewing?<button className="ss-back" onClick={()=>{setViewing(false);requestAnimationFrame(()=>{if(scroll.current)scroll.current.scrollTop=scrollTop.current;});}}><Icon name="chevron-left"/>返回 {total} 条搜索结果</button>:status==='ready'||status==='more'||status==='locating'?`${total} 条结果 · 当前聊天的全部记录`:''}</div>
    <div className="ss-results" ref={scroll} hidden={viewing} aria-label="消息搜索结果" tabIndex={0}>{error&&<p className="gr-error" role="alert">{error} <button onClick={()=>setRetry(v=>v+1)}>重试</button></p>}{status==='idle'?<p className="ss-empty">输入关键词，或选择发言人和日期。</p>:status==='loading'?<p className="ss-empty">正在搜索…</p>:<><ol>{results.map(m=><li key={m.id}><button className="ss-result" aria-current={selected===m.id?'true':undefined} disabled={status==='locating'} onClick={()=>void jump(m.id)}><span className="ss-result-meta"><strong>{m.sender==='user'?username:contacts.find(c=>c.id===m.senderMemberId)?.name??m.sender}</strong><time>{new Date(m.ts).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}</time></span><span className="ss-excerpt">{m.content||'附件消息'}</span>{status==='locating'&&selected===m.id&&<span className="ss-locating">正在定位…</span>}</button></li>)}</ol>{!results.length&&status!=='error'&&<p className="ss-empty">没有找到匹配的消息。</p>}{results.length<total&&<button className="gr-button ss-more" disabled={status==='more'} onClick={()=>void more()}>{status==='more'?'正在加载…':'查看更多结果'}</button>}</>}</div>
  </section>;
}
