import {useId,useRef,useState} from 'react';
import {Icon,Menu,MenuItem} from './ui';
export interface SelectOption {value:string;label:string;detail?:string;disabled?:boolean}
export interface SelectGroup {label?:string;options:SelectOption[]}
export function SelectMenu({id,label,value,groups,onChange,disabled=false,className=''}:{id?:string;label:string;value:string;groups:SelectGroup[];onChange:(value:string)=>void;disabled?:boolean;className?:string}) {
  const textId=useId(),trigger=useRef<HTMLButtonElement>(null),[anchor,setAnchor]=useState<{x:number;y:number;width:number}|null>(null),option=groups.flatMap(group=>group.options).find(option=>option.value===value),text=option?`${option.label}${option.detail?`（${option.detail}）`:''}`:'请选择';
  const open=()=>{if(disabled)return;const box=trigger.current!.getBoundingClientRect();setAnchor({x:box.left,y:box.bottom+4,width:Math.max(228,box.width)});};
  return <><button id={id} ref={trigger} type="button" className={`gr-choice-select ${className}`} aria-label={label} aria-describedby={textId} aria-haspopup="menu" aria-expanded={!!anchor} disabled={disabled} title={text} onClick={()=>anchor?setAnchor(null):open()} onKeyDown={event=>{if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();event.stopPropagation();open();}}}><span id={textId}>{text}</span><Icon name="chevron-down"/></button>{anchor&&<Menu {...anchor} trigger={trigger.current} label={label} onClose={()=>setAnchor(null)}>{groups.filter(group=>group.options.length>0).map((group,index)=><div key={group.label??index} role={group.label?'group':undefined} aria-label={group.label}>{index>0&&<hr className="gr-menu-divider"/>}{group.label&&<div className="gr-menu-note gr-small" aria-hidden="true">{group.label}</div>}{group.options.map(option=><MenuItem key={option.value} data-value={option.value} role="menuitemradio" aria-checked={value===option.value} disabled={option.disabled} meta={value===option.value?<Icon name="check"/>:undefined} onClick={()=>{setAnchor(null);onChange(option.value);}}>{option.label}{option.detail&&<small className="gr-small">（{option.detail}）</small>}</MenuItem>)}</div>)}</Menu>}</>;
}
