import { useEffect, useId, useRef, useState, type ReactNode } from 'react';
import { createPortal } from 'react-dom';
import * as api from '../api/client';
import { availableThinkingLevels } from '../components/thinking-levels';
import { Avatar, Icon, IconButton, Modal, errorText } from './ui';
import providerIcons from './provider-icons.json';
export function ProviderIcon({slug}:{slug:string}) {const id=useId().replace(/[^a-z0-9]/gi,''),brand=(providerIcons.providers as Record<string,string|null>)[slug]??'',asset=(providerIcons.brands as Record<string,{viewBox:string;svg:string;fillRule?:string}>)[brand];return asset?<svg className="ma-provider-icon" data-brand={brand} viewBox={asset.viewBox} fill="currentColor" fillRule={asset.fillRule as 'evenodd'|'nonzero'|undefined} aria-hidden="true" dangerouslySetInnerHTML={{__html:asset.svg.replaceAll('__MA_ICON_PREFIX__',`provider-${id}-`)}}/>:<Icon name={slug==='endpoint'?'link':'grid-sparkle'}/>;}
export function GrokSettings({open,onClose,initialTab='models'}:{open:boolean;onClose:()=>void;initialTab?:'models'|'usage'}) {
  const [tab,setTab]=useState(initialTab),[dirty,setDirty]=useState(false),[pending,setPending]=useState<(()=>void)|null>(null),ref=useRef<HTMLDialogElement>(null);
  useEffect(()=>{if(!open)return;const prev=document.activeElement as HTMLElement|null,el=ref.current!;el.showModal();return()=>{el.close();if(prev?.isConnected)prev.focus({preventScroll:true});};},[open]);
  const guard=(action:()=>void)=>dirty?setPending(()=>action):action();if(!open)return null;
  return createPortal(<dialog ref={ref} className="gr-settings-dialog" aria-label="设置" onCancel={e=>{e.preventDefault();guard(onClose);}}><div className="gr-settings-layout"><nav className="gr-settings-nav" aria-label="设置分类">{(['models','usage'] as const).map(t=><button key={t} aria-current={tab===t?'page':undefined} onClick={()=>guard(()=>{setDirty(false);setTab(t);})}><Icon name={t==='models'?'grid-sparkle':'chart-bars'}/><span>{t==='models'?'模型':'用量'}</span></button>)}</nav><section className="gr-settings-panel"><IconButton className="gr-settings-close" icon="close" label="关闭设置" onClick={()=>guard(onClose)}/><div className="gr-settings-scroll">{tab==='models'?<ModelConnections onDirty={setDirty}/>:<Usage/>}</div></section></div>{pending&&<Discard onCancel={()=>setPending(null)} onDiscard={()=>{setDirty(false);setPending(null);pending();}}/>}</dialog>,document.body);
}
function Discard({onCancel,onDiscard}:{onCancel:()=>void;onDiscard:()=>void}) {return <Modal title="放弃修改？" onClose={onCancel}><p>当前修改还没有保存。</p><div className="gr-dialog-actions"><button className="gr-button" onClick={onCancel}>继续编辑</button><button className="gr-button gr-primary" onClick={onDiscard}>放弃修改</button></div></Modal>;}
function ModelConnections({onDirty}:{onDirty:(dirty:boolean)=>void}) {
  const [profiles,setProfiles]=useState<api.PublicModelCredentialProfile[]>([]),[selected,setSelected]=useState<string|null>(null),[form,setForm]=useState<api.PublicModelCredentialProfile|'add'|null>(null),[remove,setRemove]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[catalog,setCatalog]=useState<api.ModelCatalogStatus|null>(null),[reconnect,setReconnect]=useState(false);
  const load=async()=>{try{setProfiles(await api.getModelCredentialProfiles());setCatalog(await api.getModelCatalogStatus());setError('');}catch(e){setError(errorText(e));}finally{setLoading(false);}};useEffect(()=>{void load();},[]);
  const profile=profiles.find(p=>p.id===selected);
  if(form&&form!=='add')return <ConnectionDialog existing={form} reconnect={reconnect} inline onClose={()=>{setForm(null);onDirty(false);}} onSaved={p=>{setForm(null);setSelected(p.id);onDirty(false);void load();}} onDirty={onDirty}/>;
  return <div className="ma-content" data-screen={profile?'detail':'list'} aria-label="模型接入">
    {profile?<><button className="ma-back" onClick={()=>setSelected(null)}><Icon name="chevron-left"/><span>模型</span></button><div className="ma-heading"><h1>{profile.name}</h1></div><dl className="gr-settings-card ma-facts">{[['服务',profile.providerSlug],['接入方式',profile.authType==='oauth'?'OAuth 授权':profile.authType==='api_key'?'API Key':profile.authType==='ambient'?'环境凭证':'无需认证'],['状态',profile.enabled?(profile.hasSecret||profile.authType==='none'||profile.authType==='ambient'?'已配置':'未配置凭证'):'已停用'],['接口地址',profile.baseUrl]].filter(([,v])=>v).map(([label,value])=><div className="gr-setting-row" key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><div className="ma-actions"><button className="gr-button" onClick={()=>{setReconnect(false);setForm(profile);}}>编辑</button><button className="gr-button" onClick={()=>{setReconnect(true);setForm(profile);}}>重新连接</button></div><section className="gr-settings-section ma-models"><h2>可用模型</h2><div className="gr-settings-card">{profile.models.length?profile.models.map(m=><div className="gr-setting-row ma-model-name" key={m.id}>{m.name||m.id}<small>{m.contextWindow?`${m.contextWindow.toLocaleString()} 上下文`:''}</small></div>):<p className="ma-note">这个接入没有可用模型。</p>}</div></section><div className="ma-remove"><button className="gr-button ma-danger" onClick={()=>setRemove(true)}>移除接入</button></div></>:<><div className="ma-heading"><h1>模型接入</h1></div>{loading?<p className="ma-empty">正在读取模型接入…</p>:<div className="gr-settings-card ma-list">{profiles.map(p=><button className="gr-setting-row ma-row" key={p.id} onClick={()=>setSelected(p.id)}><ProviderIcon slug={p.providerSlug}/><span>{p.name}</span><Icon name="chevron-right"/></button>)}<button className="gr-setting-row ma-add-row" onClick={()=>setForm('add')}><Icon name="add"/><span>添加模型</span></button></div>}{!loading&&!profiles.length&&<p className="ma-empty">还没有接入模型</p>}{catalog&&<div className="ma-catalog-note"><span className="gr-small">模型目录 · {catalog.freshnessLabel}</span><button className="gr-button" disabled={busy} onClick={async()=>{setBusy(true);try{const r=await api.refreshModelCatalog();if(r.error)setError(r.error);else await load();}catch(e){setError(errorText(e));}finally{setBusy(false);}}}>{busy?'正在刷新…':'刷新目录'}</button></div>}</>}
    {error&&<p className="ma-error" role="alert">{error} <button onClick={()=>void load()}>重试</button></p>}
    {form&&<ConnectionDialog existing={undefined} onClose={()=>{setForm(null);onDirty(false);}} onSaved={p=>{setForm(null);setSelected(p.id);onDirty(false);void load();}} onDirty={onDirty}/>}
    {remove&&profile&&<Modal title={`移除 ${profile.name}？`} onClose={()=>setRemove(false)}><p>使用此接入的成员将无法继续通过它调用模型。不会删除聊天记录。</p>{error&&<p className="gr-error">{error}</p>}<div className="gr-dialog-actions"><button className="gr-button" disabled={busy} onClick={()=>setRemove(false)}>取消</button><button className="gr-button ma-danger" disabled={busy} onClick={async()=>{setBusy(true);try{await api.deleteModelCredentialProfile(profile.id);setRemove(false);setSelected(null);await load();}catch(e){setError(errorText(e));}finally{setBusy(false);}}}>{busy?'正在移除…':'移除接入'}</button></div></Modal>}
  </div>;
}
const protocols:api.ModelProtocol[]=['openai-completions','openai-responses','anthropic-messages','google-generative-ai','azure-openai-responses','bedrock-converse-stream','mistral-conversations'];
function InputRow({label,children}:{label:string;children:ReactNode}) {return <div className="gr-setting-row ma-entry-row"><span>{label}</span>{children}</div>;}
function ConnectionDialog({existing,onClose,onSaved,onDirty,inline=false,reconnect=false}:{inline?:boolean;reconnect?:boolean;existing?:api.PublicModelCredentialProfile;onClose:()=>void;onSaved:(p:api.PublicModelCredentialProfile)=>void;onDirty:(v:boolean)=>void}) {
  const [providers,setProviders]=useState<api.PublicModelProvider[]>([]),[provider,setProvider]=useState<string|null>(existing?.providerSlug??null),[search,setSearch]=useState(''),[name,setName]=useState(existing?.name??''),[key,setKey]=useState(''),[url,setUrl]=useState(existing?.baseUrl??''),[protocol,setProtocol]=useState<api.ModelProtocol>(existing?.protocol??'openai-completions'),[auth,setAuth]=useState<api.ModelAuthType>(existing?.authType??'api_key'),[models,setModels]=useState<api.ModelDefinitionConfig[]>(existing?.models??[{id:'',name:'',contextWindow:undefined,maxTokens:undefined}]),[headers,setHeaders]=useState(existing?.headers?JSON.stringify(existing.headers,null,2):''),[enabled,setEnabled]=useState(existing?.enabled??true),[isDefault,setDefault]=useState(existing?.isDefault??false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[job,setJob]=useState<api.OAuthLoginJob|null>(null),[code,setCode]=useState(''),[discard,setDiscard]=useState(false),[dirty,setDirty]=useState(false);
  const current=providers.find(p=>p.providerSlug===provider),custom=provider==='endpoint'||existing?.profileKind==='custom_endpoint',alive=useRef(true),jobRef=useRef(job);jobRef.current=job;
  useEffect(()=>{alive.current=true;api.getModelProviderCatalog().then(setProviders).catch(e=>setError(errorText(e)));return()=>{alive.current=false;};},[]);
  useEffect(()=>{onDirty(dirty||!!job&&!['completed','cancelled','failed'].includes(job.status));},[dirty,job?.status]);
  useEffect(()=>{if(!job||['completed','cancelled','failed'].includes(job.status))return;let active=true;const timer=setInterval(()=>{api.getOAuthConnectionJob(job.id).then(async next=>{if(!active)return;setJob(next);}).catch(e=>{if(active)setError(errorText(e));});},1500);return()=>{active=false;clearInterval(timer);};},[job?.id,job?.status]);
  useEffect(()=>{if(job?.status!=='completed')return;let active=true;api.getModelCredentialProfiles().then(profiles=>{const profile=profiles.find(p=>p.id===job.profileId);if(active&&profile){setKey('');setCode('');setDirty(false);onSaved(profile);}else if(active)setError('授权已完成，但暂未读到接入信息，请重试读取。');}).catch(e=>{if(active)setError(errorText(e));});return()=>{active=false;};},[job?.status,job?.profileId]);
  const close=async(force=false)=>{if(busy)return;if(!force&&(dirty||job&&!['completed','cancelled','failed'].includes(job.status))){setDiscard(true);return;}if(job&&!['completed','cancelled','failed'].includes(job.status)){try{await api.cancelOAuthConnection(job.id);}catch(e){setError(errorText(e));return;}}setKey('');setCode('');onClose();};
  const edit=()=>setDirty(true);
  const save=async()=>{setError('');if(!name.trim()){setError('请填写接入名称。');return;}setBusy(true);try{let result:api.PublicModelCredentialProfile;if(existing&&!custom&&(!reconnect||auth!=='oauth')){if(reconnect&&auth==='api_key'&&!key.trim())throw Error('请输入新的 API Key。');result=await api.updateModelCredentialProfile(existing.id,{name:name.trim(),enabled,isDefault,...(key&&auth==='api_key'?{apiKey:key}:{})});setDirty(false);onSaved(result);return;}if(auth==='oauth'){const next=await api.startOAuthConnection({providerId:provider!,profileId:existing?.id,name:name.trim(),requestProfile:existing?.requestProfile??'standard'});setJob(next);setBusy(false);return;}if(!custom&&!existing){if(!key.trim()){setError('请输入 API Key。');return;}result=await api.connectModelProviderApiKey({providerSlug:provider!,apiKey:key,name:name.trim(),...(url.trim()?{baseUrlOverride:url.trim()}:{}),isDefault});}else{let extra:Record<string,string>|undefined;if(headers.trim()){extra=JSON.parse(headers);if(!extra||Array.isArray(extra)||typeof extra!=='object'||Object.values(extra).some(v=>typeof v!=='string'))throw Error('请求头须为字符串键值的 JSON 对象。');}const body:Partial<api.ModelCredentialProfileInput>={name:name.trim(),providerSlug:custom?existing?.providerSlug??'custom':provider!,profileKind:custom?'custom_endpoint':existing?.profileKind??'builtin_provider',protocol,baseUrl:url.trim()||undefined,authType:auth,requestProfile:existing?.requestProfile??'standard',enabled,isDefault,models:models.filter(m=>m.id.trim()).map(m=>({...m,id:m.id.trim(),name:m.name?.trim()||undefined})),headers:extra,...(key&&auth==='api_key'?{apiKey:key}:{})};if(custom&&!url.trim())throw Error('请输入接口地址。');if(custom&&!body.models?.length)throw Error('请至少填写一个模型 ID。');result=existing?await api.updateModelCredentialProfile(existing.id,body):await api.createModelCredentialProfile(body as api.ModelCredentialProfileInput);}if(alive.current){setKey('');setDirty(false);onSaved(result);}}catch(e){if(alive.current)setError(errorText(e));}finally{if(alive.current)setBusy(false);}};
  const select=(p:string)=>{setProvider(p);const found=providers.find(x=>x.providerSlug===p);setName(found?.displayName??'自定义端点');setAuth(found?.defaultAuthMode??'api_key');setProtocol(found?.protocol??'openai-completions');};
  const title=provider?(custom?'自定义端点':current?.displayName??existing?.name??provider):'添加模型';
  return <ConnectionFrame title={title} inline={inline} onClose={()=>void close()}>
    {!provider?<><label className="gr-search ma-provider-search"><Icon name="search"/><input type="search" aria-label="搜索供应商" placeholder="搜索供应商" value={search} onChange={e=>setSearch(e.target.value)} autoFocus/></label><div className="gr-settings-card ma-list"><button className="gr-setting-row ma-row" onClick={()=>select('endpoint')}><ProviderIcon slug="endpoint"/><span>自定义端点</span><Icon name="chevron-right"/></button></div><div className="ma-provider-scroll"><div className="gr-settings-card ma-list">{providers.filter(p=>`${p.displayName} ${p.providerSlug}`.toLocaleLowerCase().includes(search.toLocaleLowerCase())).map(p=><button className="gr-setting-row ma-row" key={p.providerSlug} onClick={()=>select(p.providerSlug)}><ProviderIcon slug={p.logoKey??p.providerSlug}/><span>{p.displayName}</span><Icon name="chevron-right"/></button>)}</div></div></>:<>
    {!existing&&!job&&<button className="ma-back" onClick={()=>{if(dirty){setDiscard(true);return;}setProvider(null);}}><Icon name="chevron-left"/>返回供应商</button>}
    <form onSubmit={e=>{e.preventDefault();void save();}}><div className="gr-settings-card"><InputRow label="接入名称"><input className="ma-control" aria-label="接入名称" value={name} onChange={e=>{setName(e.target.value);edit();}} disabled={busy}/></InputRow>
    {(custom||(current?.authModes.length??0)>1)&&<InputRow label="接入方式"><select className="ma-control" aria-label="接入方式" value={auth} onChange={e=>{setAuth(e.target.value as api.ModelAuthType);edit();}} disabled={busy||!!job}>{(custom?['api_key','none','ambient']:current?.authModes??[]).map(mode=><option key={mode} value={mode}>{mode==='api_key'?'API Key':mode==='oauth'?'OAuth 授权':mode==='ambient'?'环境凭证':'无需认证'}</option>)}</select></InputRow>}
    {custom&&<><InputRow label="协议"><select className="ma-control" aria-label="协议" value={protocol} onChange={e=>{setProtocol(e.target.value as api.ModelProtocol);edit();}}>{protocols.map(p=><option key={p}>{p}</option>)}</select></InputRow><InputRow label="接口地址"><input className="ma-control" aria-label="接口地址" type="url" required value={url} placeholder="https://api.example.com/v1" onChange={e=>{setUrl(e.target.value);edit();}}/></InputRow></>}
    {auth==='api_key'&&<InputRow label="API Key"><input className="ma-control" aria-label="API Key" type="password" autoComplete="off" value={key} placeholder={existing?.hasSecret?'已配置，留空保持不变':''} onChange={e=>{setKey(e.target.value);edit();}} disabled={busy}/></InputRow>}
    </div>
    {auth==='api_key'&&<p className="ma-note">密钥只提交给当前 Bossmode 服务，不会显示在列表中。请确认当前服务可信。</p>}
    {custom&&<><section className="gr-settings-section ma-models"><h2>模型定义</h2>{models.map((m,i)=><div className="gr-settings-card ma-model-form" key={i}>{[['id','模型 ID'],['name','显示名称'],['contextWindow','上下文长度'],['maxTokens','最大输出']].map(([field,label])=><InputRow key={field} label={label}><input className="ma-control" aria-label={`${label} ${i+1}`} type={field==='contextWindow'||field==='maxTokens'?'number':'text'} min={1} value={(m as unknown as Record<string,string|number>)[field]??''} onChange={e=>{setModels(prev=>prev.map((x,n)=>n===i?{...x,[field]:field==='contextWindow'||field==='maxTokens'?e.target.value?Number(e.target.value):undefined:e.target.value}:x));edit();}}/></InputRow>)}<InputRow label="支持推理"><input type="checkbox" aria-label={`支持推理 ${i+1}`} checked={!!m.reasoning} onChange={e=>{setModels(prev=>prev.map((x,n)=>n===i?{...x,reasoning:e.target.checked}:x));edit();}}/></InputRow><InputRow label="支持图片"><input type="checkbox" aria-label={`支持图片 ${i+1}`} checked={m.input?.includes('image')??false} onChange={e=>{setModels(prev=>prev.map((x,n)=>n===i?{...x,input:e.target.checked?['text','image']:['text']}:x));edit();}}/></InputRow>{models.length>1&&<button type="button" className="gr-button ma-danger" onClick={()=>{setModels(p=>p.filter((_,n)=>n!==i));edit();}}>移除此模型</button>}</div>)}<div className="ma-actions"><button type="button" className="gr-button" onClick={()=>{setModels(p=>[...p,{id:''}]);edit();}}>添加模型定义</button><button type="button" className="gr-button" disabled={busy} onClick={async()=>{setBusy(true);try{const found=await api.discoverModelCredentialModels({id:existing?.id,baseUrl:url,protocol,authType:auth,...(key?{apiKey:key}:{}),providerSlug:existing?.providerSlug??'custom'});setModels(found.models);setError(found.warnings.join('；'));edit();}catch(e){setError(errorText(e));}finally{setBusy(false);}}}>读取模型列表</button></div></section><details className="ma-advanced"><summary>高级设置</summary><div className="gr-field"><label>请求头（JSON）</label><textarea aria-label="请求头" value={headers} onChange={e=>{setHeaders(e.target.value);edit();}}/></div><label><input type="checkbox" checked={enabled} onChange={e=>{setEnabled(e.target.checked);edit();}}/>启用此接入</label><label><input type="checkbox" checked={isDefault} onChange={e=>{setDefault(e.target.checked);edit();}}/>设为默认接入</label></details></>}
    {job&&<div className="ma-auth" role="status"><p>{job.status==='failed'?job.error||'授权失败':job.status==='cancelled'?'授权已取消':job.status==='completed'?'授权完成':job.prompt||'等待授权…'}</p>{job.authUrl&&/^https?:\/\//.test(job.authUrl)&&<a className="gr-button" href={job.authUrl} target="_blank" rel="noopener noreferrer">打开授权页面</a>}{job.userCode&&!job.deviceCode&&<p>验证码：<code>{job.userCode}</code></p>}{job.deviceCode&&<p>验证码：<code>{job.deviceCode.userCode}</code><br/><a href={job.deviceCode.verificationUri} target="_blank" rel="noopener noreferrer">前往设备授权</a></p>}{job.status==='awaiting_input'&&<><input className="ma-control" aria-label="授权返回码" value={code} onChange={e=>setCode(e.target.value)} autoComplete="off"/><button type="button" className="gr-button" disabled={busy||!code.trim()} onClick={async()=>{setBusy(true);try{setJob(await api.submitOAuthConnectionInput(job.id,code));setCode('');}catch(e){setError(errorText(e));}finally{setBusy(false);}}}>提交授权码</button></>}{job.selectPrompt&&<select aria-label={job.selectPrompt.message} onChange={async e=>{if(!e.target.value)return;setBusy(true);try{setJob(await api.submitOAuthConnectionInput(job.id,e.target.value));}catch(error){setError(errorText(error));}finally{setBusy(false);}}}><option value="">{job.selectPrompt.message}</option>{job.selectPrompt.options.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select>}{!['completed','cancelled','failed'].includes(job.status)&&<button type="button" className="gr-button" onClick={async()=>{try{setJob(await api.cancelOAuthConnection(job.id));}catch(e){setError(errorText(e));}}}>取消授权</button>}</div>}
    {error&&<p className="ma-error" role="alert">{error}</p>}<div className="ma-actions"><button type="submit" className="gr-button gr-primary" disabled={busy||!!job&&!['failed','cancelled'].includes(job.status)}>{busy?'正在连接…':auth==='oauth'?'开始授权':existing?'保存':'连接'}</button><button type="button" className="gr-button" disabled={busy} onClick={()=>void close()}>取消</button></div></form></>}
    {error&&!provider&&<p className="ma-error">{error}</p>}{discard&&<Discard onCancel={()=>setDiscard(false)} onDiscard={()=>void close(true)}/>} 
  </ConnectionFrame>;
}
function ConnectionFrame({title,inline,onClose,children}:{title:string;inline:boolean;onClose:()=>void;children:ReactNode}) {return inline?<div className="ma-content" data-screen="form"><button className="ma-back" onClick={onClose}><Icon name="chevron-left"/><span>接入详情</span></button><div className="ma-heading"><h1>{title}</h1></div>{children}</div>:<Modal title={title} className="ma-add-dialog" onClose={onClose}>{children}</Modal>;}
export function GrokModelPicker({memberId,onSaved,onClose}:{memberId:string;onSaved:()=>void;onClose:()=>void}) {
  const [models,setModels]=useState<api.AvailableModelOption[]>([]),[member,setMember]=useState<api.MemberDetail|null>(null),[query,setQuery]=useState(''),[selected,setSelected]=useState(''),[thinking,setThinking]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{let live=true;Promise.all([api.getAvailableModels(),api.getMemberDetail(memberId)]).then(([models,member])=>{if(!live)return;setModels(models);setMember(member);setSelected(models.find(m=>m.profileId===member.global?.credentialId&&m.ref===member.global?.model)?.profileId+'|'+member.global?.model);setThinking(member.global?.thinkingLevel??'');}).catch(e=>{if(live)setError(errorText(e));});return()=>{live=false;};},[memberId]);
  const option=models.find(m=>`${m.profileId}|${m.ref}`===selected),levels=availableThinkingLevels(option),labels:Record<string,string>={default:'默认',off:'关闭',minimal:'最低',low:'低',medium:'中',high:'高',xhigh:'极高',max:'最高'};
  return <Modal title={`${member?.name??'成员'} · 模型`} onClose={()=>{if(!busy)onClose();}}><label className="gr-search ma-provider-search"><Icon name="search"/><input aria-label="搜索模型" placeholder="搜索模型" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="ma-member-models" role="listbox" aria-label="选择模型">{models.filter(m=>`${m.displayName||m.modelId} ${m.profileName}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())).map(m=><button className="gr-menu-item" key={`${m.profileId}|${m.ref}`} role="option" aria-selected={selected===`${m.profileId}|${m.ref}`} onClick={()=>{setSelected(`${m.profileId}|${m.ref}`);if(!availableThinkingLevels(m).some(l=>l.value===thinking))setThinking('');}}><span className="gr-menu-copy">{m.displayName||m.modelId}<small className="gr-small"> · {m.profileName}</small></span>{selected===`${m.profileId}|${m.ref}`&&<Icon name="check"/>}</button>)}</div>{!models.length&&<p className="ma-note">没有可选模型，请先从用户菜单 → 设置 → 模型添加接入。</p>}{option&&<div className="gr-field"><label htmlFor="memberThinking">思考强度</label><select id="memberThinking" className="ma-control" value={thinking} onChange={e=>setThinking(e.target.value)}>{levels.map(l=><option key={l.label} value={l.value??''}>{labels[l.label]??l.label}</option>)}</select></div>}{error&&<p className="ma-error" role="alert">{error}</p>}<div className="gr-dialog-actions"><button className="gr-button" disabled={busy} onClick={onClose}>取消</button><button className="gr-button gr-primary" disabled={!option||busy} onClick={async()=>{setBusy(true);try{await api.patchGlobalMember(memberId,{model:option!.ref,credentialId:option!.profileId,thinkingLevel:thinking||null});onSaved();onClose();}catch(e){setError(errorText(e));}finally{setBusy(false);}}}>{busy?'正在保存…':'保存'}</button></div></Modal>;
}
function Usage() {
  const today=new Date().toISOString().slice(0,10),ago=(n:number)=>new Date(Date.now()-n*86400000).toISOString().slice(0,10),[preset,setPreset]=useState('30'),[from,setFrom]=useState(ago(29)),[to,setTo]=useState(today),[report,setReport]=useState<api.UsageResponse|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0);
  const start=preset==='all'?undefined:preset==='custom'?from:ago(Number(preset)-1),end=preset==='custom'?to:today;
  useEffect(()=>{let live=true;setReport(null);setError('');if(!end||preset==='custom'&&(!start||start>end||end>today)){setError('请选择有效日期，结束日期不能早于开始日期或晚于今天。');setLoading(false);return;}setLoading(true);api.getPlatformUsage({from:start,to:end}).then(r=>{if(live)setReport(r);}).catch(e=>{if(live)setError(errorText(e));}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[start,end,retry]);
  const sum=(row:{inputTokens:number;outputTokens:number;cacheRead:number;cacheWrite:number})=>row.inputTokens+row.outputTokens+row.cacheRead+row.cacheWrite,total=report?sum(report.kpis):null,rows=new Map<string,{id:string;name:string;tokens:number}>();for(const r of report?.breakdown??[]){const prev=rows.get(r.memberId)??{id:r.memberId,name:r.memberName??r.agent??r.memberId,tokens:0};prev.tokens+=sum(r);rows.set(r.memberId,prev);}
  return <div className="gu-page"><div className="gu-heading"><div className="gu-title"><h1>用量</h1></div><div className="gu-range-control"><label htmlFor="guPreset">时间</label><select id="guPreset" className="gu-preset" value={preset} onChange={e=>setPreset(e.target.value)}>{[['7','近 7 天'],['30','近 30 天'],['90','近 90 天'],['all','全部时间'],['custom','自定义']].map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></div></div>{preset==='custom'&&<div className="gu-custom"><label>开始日期<input className="gu-date" type="date" aria-label="开始日期" max={today} value={from} onChange={e=>setFrom(e.target.value)}/></label><span>—</span><label>结束日期<input className="gu-date" type="date" aria-label="结束日期" max={today} value={to} onChange={e=>setTo(e.target.value)}/></label></div>}<p className="gu-range-note">{start?`${start} — ${end}`:`全部时间 · 截至 ${end}`} · UTC</p><section className="gr-settings-card gu-total" aria-label="总消耗"><h2>总消耗</h2><div className="gu-total-line"><strong>{total===null?'—':total.toLocaleString('zh-CN')}</strong><span>Token</span></div><p>含输入、输出与缓存 Token</p></section><section className="gr-settings-section gu-breakdown"><header><h2>按成员</h2><span>Token</span></header><div className="gr-settings-card gu-list">{loading?<p className="gu-state">正在加载用量…</p>:error?<div className="gu-state" role="alert"><p>{error}</p><button className="gr-button" onClick={()=>setRetry(v=>v+1)}>重试</button></div>:!rows.size?<p className="gu-state">这个时间段没有用量记录。</p>:<ul className="gu-members">{[...rows.values()].sort((a,b)=>b.tokens-a.tokens).map(r=><li className="gu-member-row" key={r.id}><Avatar id={r.id} size={28}/><div className="gu-member-body"><div className="gu-member-top"><span className="gu-member-name">{r.name}</span><span className="gu-member-value">{r.tokens.toLocaleString('zh-CN')}</span></div><div className="gu-member-comparison"><span className="gu-member-track"><span className="gu-member-fill" style={{width:`${total?r.tokens/total*100:0}%`}}/></span><span className="gu-member-share">{(total?r.tokens/total*100:0).toFixed(1)}%</span></div></div></li>)}</ul>}</div></section></div>;
}
