import {Fragment,useEffect,useRef,useState} from 'react';
import {apiFetch,apiFetchBlob,type MemberWorkspaceEntry} from '../api/client';
import type {ViewFile} from './Files';
import {Icon,IconButton,bytes,errorText} from './ui';
interface Entry {name:string;path:string;kind:'file'|'directory'|'link'|'other';size:number;modifiedAt:number;readable:boolean;reason?:string}
interface Listing {path:string;entries:Entry[];total:number;hasMore:boolean;nextOffset:number|null}
const endpoint=(id:string,workspace:string)=>`/api/members/${encodeURIComponent(id)}/workspaces/${encodeURIComponent(workspace)}`;
export function WorkspaceAssets({id,onOpenFile}:{id:string;onOpenFile:(file:ViewFile)=>void}) {
 const [registry,setRegistry]=useState<{active:string;workspaces:MemberWorkspaceEntry[]}|null>(null),[workspace,setWorkspace]=useState(''),[path,setPath]=useState(''),[listing,setListing]=useState<Listing|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState(''),[attempt,setAttempt]=useState(0),[registryAttempt,setRegistryAttempt]=useState(0),[moreBusy,setMoreBusy]=useState(false),[moreError,setMoreError]=useState('');
 const listRef=useRef<HTMLDivElement>(null),request=useRef<AbortController|null>(null),positions=useRef(new Map<string,number>()),focusPath=useRef('');
 useEffect(()=>{const abort=new AbortController();setBusy(true);setError('');apiFetch<{active:string;workspaces:MemberWorkspaceEntry[]}>(`/api/members/${encodeURIComponent(id)}/workspaces`,{signal:abort.signal}).then(data=>{if(!abort.signal.aborted){setRegistry(data);setWorkspace(data.active);}}).catch(e=>{if(!abort.signal.aborted){setError(errorText(e));setBusy(false);}});return()=>abort.abort();},[id,registryAttempt]);
 useEffect(()=>{
  if(!workspace)return;const abort=new AbortController();request.current=abort;setListing(null);setBusy(true);setError('');setMoreError('');setMoreBusy(false);
  apiFetch<Listing>(`${endpoint(id,workspace)}/files?${new URLSearchParams({path})}`,{signal:abort.signal}).then(data=>{if(!abort.signal.aborted){setListing(data);setBusy(false);}}).catch(e=>{if(!abort.signal.aborted){setError(errorText(e));setBusy(false);}});
  return()=>{abort.abort();request.current=null;};
 },[id,workspace,path,attempt]);
 useEffect(()=>{if(busy||!listing)return;const list=listRef.current;if(list){list.scrollTop=positions.current.get(`${workspace}:${path}`)??0;if(focusPath.current){const button=[...list.querySelectorAll<HTMLButtonElement>('[data-path]')].find(el=>el.dataset.path===focusPath.current);button?.focus({preventScroll:true});focusPath.current='';}}},[busy]);
 const go=(next:string)=>{if(next===path)return;request.current?.abort();setBusy(true);setListing(null);setError('');positions.current.set(`${workspace}:${path}`,listRef.current?.scrollTop??0);focusPath.current=path.startsWith(next)?path.slice(0,path.indexOf('/',next?next.length+1:0)===-1?undefined:path.indexOf('/',next?next.length+1:0)):'';setPath(next);};
 const loadMore=async()=>{if(!listing?.hasMore||moreBusy||!request.current)return;const signal=request.current.signal;setMoreBusy(true);setMoreError('');try{const data=await apiFetch<Listing>(`${endpoint(id,workspace)}/files?${new URLSearchParams({path,offset:String(listing.nextOffset)})}`,{signal});if(!signal.aborted)setListing(previous=>previous?{...data,entries:[...previous.entries,...data.entries.filter(e=>!previous.entries.some(old=>old.path===e.path))]}:data);}catch(e){if(!signal.aborted)setMoreError(errorText(e));}finally{if(!signal.aborted)setMoreBusy(false);}};
 const selected=registry?.workspaces.find(w=>w.id===workspace),parts=path?path.split('/'):[];
 return <>
  <div className="ax-toolbar"><div className="ax-workspace-row"><select className="gr-select ax-workspace" aria-label="选择工作区" disabled={!registry} value={workspace} onChange={e=>{request.current?.abort();setBusy(true);setListing(null);setError('');setWorkspace(e.target.value);setPath('');focusPath.current='';}}>{!registry&&<option value="">工作区</option>}{registry?.workspaces.map(w=><option key={w.id} value={w.id}>{w.id}{w.id===registry.active?' · 当前':''}</option>)}</select><span className="ax-workspace-meta">{selected?selected.kind==='ssh'?'远端':'本机':''}</span><IconButton icon="arrows-cw" label="刷新目录" disabled={busy||!registry} onClick={()=>setAttempt(v=>v+1)}/></div><p className="ax-root" title={selected?.root}>{selected?.kind==='ssh'?`${selected.user}@${selected.host}:`:''}{selected?.root}</p><nav className="ax-path" aria-label="工作区路径"><Icon name="folder"/>{path?<button onClick={()=>go('')} aria-label="返回工作区根目录">{workspace}</button>:<span aria-current="location">{workspace||'正在读取…'}</span>}{parts.map((part,index)=><Fragment key={index}><Icon name="chevron-right"/>{index===parts.length-1?<span aria-current="location" title={part}>{part}</span>:<button onClick={()=>go(parts.slice(0,index+1).join('/'))} title={part}>{part}</button>}</Fragment>)}</nav></div>
  <div className="ax-list" ref={listRef} aria-label="工作区文件" aria-busy={busy} tabIndex={0}>
   {busy?<p className="ax-empty" role="status">正在读取目录…</p>:error?<div className="ax-empty" role="alert"><span>{error}</span><button className="gr-button" onClick={()=>registry?setAttempt(v=>v+1):setRegistryAttempt(v=>v+1)}>重试</button></div>:<>
    {path&&<button className="ax-file-row" onClick={()=>go(parts.slice(0,-1).join('/'))}><Icon name="chevron-left"/><span className="ax-file-name">上一级</span></button>}
    {!listing?.entries.length?<p className="ax-empty">此目录没有可浏览的文件。</p>:<ul className="ax-files">{listing.entries.map(entry=><li key={entry.path}><button className="ax-file-row" data-path={entry.path} disabled={!entry.readable} title={entry.reason??entry.name} aria-label={`${entry.kind==='directory'?'打开文件夹':'查看文件'} ${entry.name}${entry.readable?'':'，不可访问或超出工作区'}`} onClick={()=>entry.kind==='directory'?go(entry.path):onOpenFile({id:`${id}:${workspace}:${entry.path}`,name:entry.name,path:entry.path,size:entry.size,load:signal=>apiFetchBlob(`${endpoint(id,workspace)}/file?${new URLSearchParams({path:entry.path})}`,{signal})})}><Icon name={entry.kind==='directory'?'folder':entry.readable?'file':'lock'}/><span className="ax-file-name">{entry.name}</span>{entry.kind==='directory'?<Icon name="chevron-right"/>:<small>{entry.readable?bytes(entry.size):'不可访问'}</small>}</button></li>)}</ul>}
    {moreError&&<p className="gr-error" role="alert">{moreError}</p>}{listing?.hasMore&&<button className="gr-button ax-more" disabled={moreBusy} onClick={()=>void loadMore()}>{moreBusy?'正在读取…':moreError?'重试加载':'加载更多'}</button>}
   </>}
  </div><footer className="ax-footer"><span>{listing?`${listing.entries.length} / ${listing.total} 项`:'工作区文件'}</span><span>只读 · 私钥不可读</span></footer>
 </>;
}
