import {describe,it,expect} from 'vitest';
import {endpointDraft,serializeEndpoint,validateHeaderDrafts,validateEndpointUrl,FormError} from '../../web/src/grok/model-form.js';
const draft=()=>({...endpointDraft(),url:'https://models.example.test/v1',modelId:'sample'});
describe('Grok endpoint fields preserve Pi model semantics',()=>{
 it('keeps zero distinct from unknown prices',()=>{const d=draft();d.prices.input='0';d.prices.output='1.2';const model=serializeEndpoint(d);expect(model.cost).toEqual({input:0,output:1.2});expect(model.cost?.cacheRead).toBeUndefined();});
 it('maps inherit to omitted, unsupported to null and explicit values to strings',()=>{const d=draft();d.reasoning=true;d.levels.high={mode:'value',value:'high-custom'};d.levels.max={mode:'unsupported',value:''};expect(serializeEndpoint(d).thinkingLevelMap).toEqual({high:'high-custom',max:null});});
 it('keeps dormant values in the draft but does not send them when reasoning is off',()=>{const d=draft();d.levels.high={mode:'value',value:'kept'};d.format='deepseek';expect(serializeEndpoint(d).thinkingLevelMap).toBeUndefined();expect(d.levels.high.value).toBe('kept');d.reasoning=true;expect(serializeEndpoint(d).compat).toEqual({thinkingFormat:'deepseek'});d.protocol='anthropic-messages';expect(serializeEndpoint(d).compat).toBeUndefined();expect(d.format).toBe('deepseek');});
 it('does not allow empty explicit mapping, invalid numeric fields, or negative prices',()=>{let d=draft();d.reasoning=true;d.levels.high.mode='value';expect(()=>serializeEndpoint(d)).toThrow(FormError);d=draft();d.context='1.2';expect(()=>serializeEndpoint(d)).toThrow('正整数');d=draft();d.prices.input='-1';expect(()=>serializeEndpoint(d)).toThrow('非负数');});
 it('rejects credential-bearing, query, hash and non-http endpoint URLs',()=>{for(const value of ['file:///a','https://u:p@example.test/v1','https://example.test/?token=x','https://example.test/#h'])expect(()=>validateEndpointUrl(value)).toThrow();expect(validateEndpointUrl(' http://127.0.0.1:1234/v1 ')).toBe('http://127.0.0.1:1234/v1');});
 it('requires real values for new headers, permits keeping existing hidden values and rejects case duplicates',()=>{expect(()=>validateHeaderDrafts([{name:'X-Token',value:'',stored:true}])).not.toThrow();expect(()=>validateHeaderDrafts([{name:'X-Token',value:''}])).toThrow();expect(()=>validateHeaderDrafts([{name:'X-Token',value:'a'},{name:'x-token',value:'b'}])).toThrow('重复');expect(()=>validateHeaderDrafts([{name:'x',value:'a\r\nb'}])).toThrow('换行');});
});
