import { afterEach, beforeEach, expect, it } from "vitest";
import { existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { coreFixture } from "../helpers/core-fixture.js";
import { MemberArchivesRepository } from "../../src/storage/repositories/member-archives.js";
import { MemberArchiveService } from "../../src/workspace/member-archive-lifecycle.js";
let fixture: ReturnType<typeof coreFixture>;
let root: string;
beforeEach(() => { fixture = coreFixture(); root = fixture.root; });
afterEach(() => fixture.close());
it("archive retains SQL metadata and literal persona bytes", async () => {
  const { createMember, getMember, memberDir } = await import("../../src/workspace/member-registry.js");
  const m = createMember({ name: "before", title: "Engineer", model: "p/m", credentialId: "credential-ref", thinkingLevel: "high", skills: ["skill-a"], mcpServers: ["server-a"] });
  const markdown = "---\nname: this is Markdown, not identity\n---\n\n自由正文\n\n";
  writeFileSync(join(memberDir(m.id), "persona.md"), markdown);
  expect(existsSync(join(memberDir(m.id), "member.json"))).toBe(false);
  const { archived } = await new MemberArchiveService(fixture.db, root, { quiesce: async () => {} }).archive(m.id, { confirm: true });
  expect(getMember(m.id)).toBeNull();
  expect(fixture.db.get("SELECT archive_path FROM members WHERE id=?", m.id)).toEqual({ archive_path: archived });
  expect(new MemberArchivesRepository(fixture.db).get(archived, m.name)).toMatchObject({ title: "Engineer", global: m.global });
  expect(existsSync(join(root, archived, "member.json"))).toBe(false);
});
